package com.dgt.backend.access;
import java.util.List;
final class ExtendedPagePermissions {
 static final List<PagePermissions.Page> PAGES=List.of(
 new PagePermissions.Page("DAILY_CLOSING_PAGE_DASHBOARD","Dashboard","Everyday Closing Reports Permissions",true),
 new PagePermissions.Page("DAILY_CLOSING_PAGE_STORE","Store","Everyday Closing Reports Permissions",true),
 new PagePermissions.Page("DAILY_CLOSING_PAGE_DELI","Deli","Everyday Closing Reports Permissions",false),
 new PagePermissions.Page("DAILY_CLOSING_PAGE_CHECK_CASHING","Check Cashing","Everyday Closing Reports Permissions",false),
 new PagePermissions.Page("DAILY_CLOSING_PAGE_REPORTS","Reports","Everyday Closing Reports Permissions",true),
 new PagePermissions.Page("DAILY_CLOSING_PAGE_SETTINGS","Settings","Everyday Closing Reports Permissions",false),
 new PagePermissions.Page("FINANCIAL_PAGE_DASHBOARD","Dashboard","Financial and Payment Services Permissions",false),
 new PagePermissions.Page("FINANCIAL_PAGE_MONEY_ORDER","Money order","Financial and Payment Services Permissions",false),
 new PagePermissions.Page("FINANCIAL_PAGE_BILL_PAY","Bill pay","Financial and Payment Services Permissions",false),
 new PagePermissions.Page("FINANCIAL_PAGE_MONEY_TRANSFER","Money transfer","Financial and Payment Services Permissions",false),
 new PagePermissions.Page("FINANCIAL_PAGE_ATM","ATM","Financial and Payment Services Permissions",false),
 new PagePermissions.Page("FINANCIAL_PAGE_REPORTS","Reports","Financial and Payment Services Permissions",false),
 new PagePermissions.Page("TENDERS_PAGE_DASHBOARD","Dashboard","Tender Types Permissions",false),
 new PagePermissions.Page("TENDERS_PAGE_CREDIT_CARD","Credit card","Tender Types Permissions",true),
 new PagePermissions.Page("TENDERS_PAGE_EBT_FOODSTAMPS","EBT/Foodstamps","Tender Types Permissions",true),
 new PagePermissions.Page("TENDERS_PAGE_FLEET_CARDS","Fleet cards","Tender Types Permissions",true),
 new PagePermissions.Page("TENDERS_PAGE_CUSTOMER_ACCOUNTS","Customer accounts","Tender Types Permissions",false),
 new PagePermissions.Page("TENDERS_PAGE_REPORTS","Reports","Tender Types Permissions",true),
 new PagePermissions.Page("BANKING_PAGE_DASHBOARD","Dashboard","Banking Management Permissions",false),
 new PagePermissions.Page("BANKING_PAGE_BANK_LEDGER","Bank Ledger","Banking Management Permissions",false),
 new PagePermissions.Page("BANKING_PAGE_FUND_TRANSFER","Fund transfer","Banking Management Permissions",false),
 new PagePermissions.Page("BANKING_PAGE_RECONCILE","Reconcile","Banking Management Permissions",false),
 new PagePermissions.Page("BANKING_PAGE_BANK_ACCOUNTS","Bank accounts","Banking Management Permissions",false),
 new PagePermissions.Page("SALES_REPORTS_PAGE_NET_WORTH","Net worth","Sales and Performance Reports Permissions",false),
 new PagePermissions.Page("SALES_REPORTS_PAGE_POS_REPORT","POS report","Sales and Performance Reports Permissions",true),
 new PagePermissions.Page("SALES_REPORTS_PAGE_EXPENSES_CPA","Expenses CPA","Sales and Performance Reports Permissions",false),
 new PagePermissions.Page("SALES_REPORTS_PAGE_OTHER_INCOME_CPA","Other income CPA","Sales and Performance Reports Permissions",false),
 new PagePermissions.Page("INVENTORY_VALUATION_PAGE_CURRENT_STOCK","Current stock","Inventory Valuation Permissions",true),
 new PagePermissions.Page("INVENTORY_VALUATION_PAGE_VALUATION","Valuation","Inventory Valuation Permissions",false),
 new PagePermissions.Page("PRICE_BOOK_PAGE_STATISTICS","Statistics","Price Book Permissions",true),
 new PagePermissions.Page("PRICE_BOOK_PAGE_ITEMS","Items","Price Book Permissions",true),
 new PagePermissions.Page("PRICE_BOOK_PAGE_NEW_ARRIVALS","New arrivals","Price Book Permissions",true),
 new PagePermissions.Page("PRICE_BOOK_PAGE_BULK_UPDATE","Bulk update","Price Book Permissions",true),
 new PagePermissions.Page("PRICE_BOOK_PAGE_PROMOTIONS","Promotions","Price Book Permissions",true),
 new PagePermissions.Page("PRICE_BOOK_PAGE_DISCOUNTS","Discounts","Price Book Permissions",true),
 new PagePermissions.Page("PRICE_BOOK_PAGE_INVENTORY_BY_ITEM_CURRENT_STOCK","Inventory by item (current stock)","Price Book Permissions",true),
 new PagePermissions.Page("PRICE_BOOK_PAGE_PRICE_GROUPS","Price groups","Price Book Permissions",true),
 new PagePermissions.Page("PRICE_BOOK_PAGE_VENDOR_MANAGEMENT","Vendor management","Price Book Permissions",true),
 new PagePermissions.Page("PRICE_BOOK_PAGE_REBATE_MANAGEMENT","Rebate management","Price Book Permissions",true),
 new PagePermissions.Page("WORKWEEK_PAGE_EMPLOYEES","Employees","Workweek Permissions",true),
 new PagePermissions.Page("WORKWEEK_PAGE_WEEK_SCHEDULE","Week Schedule","Workweek Permissions",true),
 new PagePermissions.Page("WORKWEEK_PAGE_TIME_ATTENDANCE","Time & Attendance","Workweek Permissions",false),
 new PagePermissions.Page("WORKWEEK_PAGE_TIME_OFF_REQUEST","Time Off Request","Workweek Permissions",true),
 new PagePermissions.Page("WORKWEEK_PAGE_TIME_OFF_APPROVALS","Time Off Approvals","Workweek Permissions",true),
 new PagePermissions.Page("PAYROLL_PAGE_RUN_PAYROLL","Run Payroll","Payroll Permissions",false),
 new PagePermissions.Page("PAYROLL_PAGE_PAYSTUBS","Paystubs","Payroll Permissions",false),
 new PagePermissions.Page("PAYROLL_PAGE_DIRECT_DEPOSIT","Direct Deposit","Payroll Permissions",false),
 new PagePermissions.Page("PAYROLL_PAGE_TAXES_FILING","Taxes & Filing","Payroll Permissions",false),
 new PagePermissions.Page("PAYROLL_PAGE_PAYROLL_LEDGER","Payroll Ledger","Payroll Permissions",false));
 static final List<PagePermissions.Child> CHILDREN=List.of(
 new PagePermissions.Child("PRICE_BOOK_PAGE_VENDOR_MANAGEMENT_VENDORS","Vendors","PRICE_BOOK_PAGE_VENDOR_MANAGEMENT","vendors",true),
 new PagePermissions.Child("PRICE_BOOK_PAGE_VENDOR_MANAGEMENT_CONTRACTS","Contracts","PRICE_BOOK_PAGE_VENDOR_MANAGEMENT","contracts",true),
 new PagePermissions.Child("PRICE_BOOK_PAGE_VENDOR_MANAGEMENT_PRICING","Pricing","PRICE_BOOK_PAGE_VENDOR_MANAGEMENT","pricing",true),
 new PagePermissions.Child("PRICE_BOOK_PAGE_VENDOR_MANAGEMENT_AUDIT","Audit Log","PRICE_BOOK_PAGE_VENDOR_MANAGEMENT","audit",true),
 new PagePermissions.Child("PRICE_BOOK_PAGE_VENDOR_MANAGEMENT_INVOICES","Vendor profile: Invoices","PRICE_BOOK_PAGE_VENDOR_MANAGEMENT","invoices",false),
 new PagePermissions.Child("PRICE_BOOK_PAGE_VENDOR_MANAGEMENT_PAYMENTS","Vendor profile: Payment History","PRICE_BOOK_PAGE_VENDOR_MANAGEMENT","payments",false),
 new PagePermissions.Child("DAILY_CLOSING_PAGE_REPORTS_DAILY_SUMMARY","Daily Summary","DAILY_CLOSING_PAGE_REPORTS","daily-summary",true),
 new PagePermissions.Child("DAILY_CLOSING_PAGE_REPORTS_DAILY_DELI_SUMMARY","Daily Deli Summary","DAILY_CLOSING_PAGE_REPORTS","daily-deli-summary",false),
 new PagePermissions.Child("DAILY_CLOSING_PAGE_REPORTS_CHECK_CASHING_SUMMARY","Check Cashing Summary","DAILY_CLOSING_PAGE_REPORTS","check-cashing-summary",false),
 new PagePermissions.Child("DAILY_CLOSING_PAGE_REPORTS_MONTHLY_TOTALS","Monthly Totals","DAILY_CLOSING_PAGE_REPORTS","monthly-totals",true),
 new PagePermissions.Child("DAILY_CLOSING_PAGE_REPORTS_DELI_MONTHLY_TOTALS","Deli Monthly Totals","DAILY_CLOSING_PAGE_REPORTS","deli-monthly-totals",false),
 new PagePermissions.Child("TENDERS_PAGE_CREDIT_CARD_SETTLEMENT","Credit Card Settlement","TENDERS_PAGE_CREDIT_CARD","settlement",true),
 new PagePermissions.Child("TENDERS_PAGE_CREDIT_CARD_BATCH_FEE","Update Batch Fee","TENDERS_PAGE_CREDIT_CARD","batch-fee",true),
 new PagePermissions.Child("TENDERS_PAGE_CREDIT_CARD_SETTINGS","Settings","TENDERS_PAGE_CREDIT_CARD","settings",true),
 new PagePermissions.Child("TENDERS_PAGE_REPORTS_CC_BATCH_LOG","Credit Card Batch Log","TENDERS_PAGE_REPORTS","cc-batch-log",true),
 new PagePermissions.Child("TENDERS_PAGE_REPORTS_CC_BALANCE","Credit Card Balance Report","TENDERS_PAGE_REPORTS","cc-balance",true),
 new PagePermissions.Child("TENDERS_PAGE_REPORTS_TENDER_BATCH_LOG","Tender Batch Log","TENDERS_PAGE_REPORTS","tender-batch-log",true),
 new PagePermissions.Child("TENDERS_PAGE_REPORTS_TENDER_BALANCE","Tender Balance Report","TENDERS_PAGE_REPORTS","tender-balance",true),
 new PagePermissions.Child("TENDERS_PAGE_CUSTOMER_ACCOUNTS_SUMMARY","Account Summary","TENDERS_PAGE_CUSTOMER_ACCOUNTS","summary",true),
 new PagePermissions.Child("TENDERS_PAGE_CUSTOMER_ACCOUNTS_AGING","Aging Report","TENDERS_PAGE_CUSTOMER_ACCOUNTS","aging",true),
 new PagePermissions.Child("FINANCIAL_PAGE_REPORTS_SETTLEMENTS","Service Settlements","FINANCIAL_PAGE_REPORTS","settlements",true),
 new PagePermissions.Child("SALES_REPORTS_PAGE_POS_REPORT_Z_REPORT","Z-Report","SALES_REPORTS_PAGE_POS_REPORT","z-report",true),
 new PagePermissions.Child("SALES_REPORTS_PAGE_POS_REPORT_DEPARTMENT_SALES","Department Sales","SALES_REPORTS_PAGE_POS_REPORT","department-sales",true),
 new PagePermissions.Child("SALES_REPORTS_PAGE_POS_REPORT_GAS_SALES","Gas Sales","SALES_REPORTS_PAGE_POS_REPORT","gas-sales",true),
 new PagePermissions.Child("SALES_REPORTS_PAGE_POS_REPORT_ITEM_SALES","Item Sales","SALES_REPORTS_PAGE_POS_REPORT","item-sales",true),
 new PagePermissions.Child("SALES_REPORTS_PAGE_POS_REPORT_ITEM_SALES_TIME","Item Sales by Date/Hour","SALES_REPORTS_PAGE_POS_REPORT","item-sales-time",true),
 new PagePermissions.Child("SALES_REPORTS_PAGE_POS_REPORT_FUEL_CREDIT_CARD","Fuel Sales by CC","SALES_REPORTS_PAGE_POS_REPORT","fuel-credit-card",true),
 new PagePermissions.Child("SALES_REPORTS_PAGE_POS_REPORT_TAX_SALES","Tax Sales Report","SALES_REPORTS_PAGE_POS_REPORT","tax-sales",true),
 new PagePermissions.Child("SALES_REPORTS_PAGE_POS_REPORT_PROFIT","Profit","SALES_REPORTS_PAGE_POS_REPORT","profit",true),
 new PagePermissions.Child("SALES_REPORTS_PAGE_POS_REPORT_ITEM_HISTORY","Item Sales History","SALES_REPORTS_PAGE_POS_REPORT","item-history",true),
 new PagePermissions.Child("SALES_REPORTS_PAGE_POS_REPORT_MANUAL_RINGUPS","Manual Ring-ups","SALES_REPORTS_PAGE_POS_REPORT","manual-ringups",true),
 new PagePermissions.Child("PRICE_BOOK_PAGE_DISCOUNTS_REASONS","Discount Reasons","PRICE_BOOK_PAGE_DISCOUNTS","reasons",true),
 new PagePermissions.Child("PRICE_BOOK_PAGE_DISCOUNTS_REPORT","Discounts Given","PRICE_BOOK_PAGE_DISCOUNTS","report",true),
 new PagePermissions.Child("PRICE_BOOK_PAGE_REBATE_MANAGEMENT_PROGRAMS","Programs","PRICE_BOOK_PAGE_REBATE_MANAGEMENT","programs",true),
 new PagePermissions.Child("PRICE_BOOK_PAGE_REBATE_MANAGEMENT_REBATE_ITEMS","Rebate Items","PRICE_BOOK_PAGE_REBATE_MANAGEMENT","rebate-items",true),
 new PagePermissions.Child("PRICE_BOOK_PAGE_REBATE_MANAGEMENT_CLAIMS_PAYMENTS","Claims & Payments","PRICE_BOOK_PAGE_REBATE_MANAGEMENT","claims-payments",true),
 new PagePermissions.Child("PRICE_BOOK_PAGE_REBATE_MANAGEMENT_REBATE_REPORTS","Rebate Reports","PRICE_BOOK_PAGE_REBATE_MANAGEMENT","rebate-reports",false),
 new PagePermissions.Child("PAYROLL_PAGE_TAXES_FILING_LIABILITY","Tax Liability","PAYROLL_PAGE_TAXES_FILING","liability",true),
 new PagePermissions.Child("PAYROLL_PAGE_TAXES_FILING_PAYMENTS","Payments Made","PAYROLL_PAGE_TAXES_FILING","payments",true),
 new PagePermissions.Child("PAYROLL_PAGE_TAXES_FILING_FORMS","Forms Summary","PAYROLL_PAGE_TAXES_FILING","forms",true),
 new PagePermissions.Child("DAILY_CLOSING_PAGE_STORE_DAILY","Daily Report","DAILY_CLOSING_PAGE_STORE","daily",true),
 new PagePermissions.Child("DAILY_CLOSING_PAGE_STORE_OTHER","Not Needed for Daily Report","DAILY_CLOSING_PAGE_STORE","other",true),
 new PagePermissions.Child("DAILY_CLOSING_PAGE_DELI_DAILY","Daily Report","DAILY_CLOSING_PAGE_DELI","daily",true),
 new PagePermissions.Child("DAILY_CLOSING_PAGE_DELI_OTHER","Not Needed for Daily Report","DAILY_CLOSING_PAGE_DELI","other",true),
 new PagePermissions.Child("DAILY_CLOSING_PAGE_CHECK_CASHING_DAILY","Daily Report","DAILY_CLOSING_PAGE_CHECK_CASHING","daily",true),
 new PagePermissions.Child("DAILY_CLOSING_PAGE_CHECK_CASHING_OTHER","Not Needed for Daily Report","DAILY_CLOSING_PAGE_CHECK_CASHING","other",true),
 new PagePermissions.Child("WORKWEEK_PAGE_EMPLOYEES_PERSONAL","Personal","WORKWEEK_PAGE_EMPLOYEES","personal",true),
 new PagePermissions.Child("WORKWEEK_PAGE_EMPLOYEES_PAY","Pay","WORKWEEK_PAGE_EMPLOYEES","pay",true),
 new PagePermissions.Child("WORKWEEK_PAGE_EMPLOYEES_DEPOSIT","Deposit","WORKWEEK_PAGE_EMPLOYEES","deposit",true),
 new PagePermissions.Child("WORKWEEK_PAGE_EMPLOYEES_DEDUCTIONS","Deductions","WORKWEEK_PAGE_EMPLOYEES","deductions",true),
 new PagePermissions.Child("WORKWEEK_PAGE_EMPLOYEES_TIMEOFF","Time off","WORKWEEK_PAGE_EMPLOYEES","timeoff",true),
 new PagePermissions.Child("WORKWEEK_PAGE_EMPLOYEES_DOCS","Documents","WORKWEEK_PAGE_EMPLOYEES","docs",true),
 new PagePermissions.Child("WORKWEEK_PAGE_WEEK_SCHEDULE_SCHEDULE","Schedule","WORKWEEK_PAGE_WEEK_SCHEDULE","schedule",true),
 new PagePermissions.Child("WORKWEEK_PAGE_WEEK_SCHEDULE_AVAILABILITY","Availability","WORKWEEK_PAGE_WEEK_SCHEDULE","availability",true),
 new PagePermissions.Child("WORKWEEK_PAGE_WEEK_SCHEDULE_COVERAGE","Shift Swaps & Coverage","WORKWEEK_PAGE_WEEK_SCHEDULE","coverage",false),
 new PagePermissions.Child("WORKWEEK_PAGE_TIME_OFF_APPROVALS_PENDING","Pending","WORKWEEK_PAGE_TIME_OFF_APPROVALS","pending",true),
 new PagePermissions.Child("WORKWEEK_PAGE_TIME_OFF_APPROVALS_ALL","All Requests","WORKWEEK_PAGE_TIME_OFF_APPROVALS","all",true));
}
