package com.dgt.backend.tender;

import com.dgt.backend.access.ScopedAccess;
import java.math.*;
import java.time.*;
import java.sql.Timestamp;
import java.util.*;
import org.springframework.boot.autoconfigure.condition.ConditionalOnProperty;
import org.springframework.http.HttpStatus;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.server.ResponseStatusException;
import tools.jackson.databind.ObjectMapper;

@RestController
@ConditionalOnProperty(name="app.tender.credit-card.enabled",havingValue="true")
@RequestMapping("/api/v1/access/stores/{store}/credit-card")
public class CreditCardController {
 private final ScopedAccess a;private final ObjectMapper json;
 public CreditCardController(ScopedAccess a,ObjectMapper json){this.a=a;this.json=json;}
 private ResponseStatusException bad(String s){return new ResponseStatusException(HttpStatus.BAD_REQUEST,s);}
 private ResponseStatusException conflict(String s){return new ResponseStatusException(HttpStatus.CONFLICT,s);}
 private void access(String store){if(a.admin(a.user(),a.company(store)))return;if(!Boolean.TRUE.equals(a.db.queryForObject("SELECT EXISTS(SELECT 1 FROM user_roles r JOIN role_types t USING(role_type_id) WHERE r.user_id=? AND r.dgt_id=? AND r.is_active AND t.is_active AND upper(t.role_type_name)='MANAGER')",Boolean.class,a.user(),store)))throw a.denied();}
 private void lock(String store){access(store);a.db.queryForObject("SELECT dgt_id FROM stores WHERE dgt_id=? FOR UPDATE",String.class,store);}
 private ZoneId zone(String store){return ZoneId.of(a.db.queryForObject("SELECT timezone FROM stores WHERE dgt_id=?",String.class,store));}
 private LocalDate day(String store,LocalDate day){if(day==null||day.isBefore(LocalDate.of(1900,1,1))||day.isAfter(LocalDate.now(zone(store))))throw bad("Choose a business date today or earlier");return day;}
 private BigDecimal n(Object v){return v==null?BigDecimal.ZERO:new BigDecimal(v.toString());}
 private BigDecimal money(BigDecimal v,boolean negative){if(v==null||v.scale()>2||v.abs().compareTo(new BigDecimal("9999999999.99"))>0||!negative&&v.signum()<0)throw bad("Enter a valid amount with at most two decimal places");return v;}
 private BigDecimal rate(Object v){BigDecimal r=n(v);if(v==null||r.signum()<0||r.compareTo(new BigDecimal("100"))>0||r.scale()>4)throw bad("Rate must be between 0 and 100 with up to four decimal places");return r;}
 private String str(String v,int max,boolean required){if(v==null)v="";v=v.trim();if(v.length()>max||required&&v.isEmpty())throw bad("Enter a value of at most "+max+" characters");return v;}
 private void version(Map<String,Object> row,String v){if(!Objects.equals(row.get("version"),v))throw conflict("Record changed; reload before saving");}
 private void audit(String store,String kind,Object id,Object before,Object after){a.audit(store,"CREDIT_CARD_"+kind,String.valueOf(id),json.writeValueAsString(Map.of("before",before,"after",after)));}
 private static final List<String> NUMBERS=List.of("default_fee_percent","per_transaction_fee","fee_difference_percent","deposit_tolerance");
 private static final List<String> FLAGS=List.of("require_fee_review","require_variance_review","enable_chargebacks","require_chargeback_reason","lock_settings_after_settlement");
 private Map<String,Object> settings(String store){var rows=a.db.queryForList("SELECT *,xmin::text AS version FROM credit_card_settings WHERE dgt_id=?",store);if(!rows.isEmpty())return rows.getFirst();var r=new LinkedHashMap<String,Object>();r.put("version","0");r.put("default_fee_percent",BigDecimal.ZERO);r.put("per_transaction_fee",BigDecimal.ZERO);r.put("fee_difference_percent",new BigDecimal("0.2"));r.put("deposit_tolerance",new BigDecimal("5"));for(String k:FLAGS)r.put(k,!k.equals("lock_settings_after_settlement"));return r;}
 private boolean locked(String store,Map<String,Object> settings){return Boolean.TRUE.equals(settings.get("lock_settings_after_settlement"))&&Boolean.TRUE.equals(a.db.queryForObject("SELECT EXISTS(SELECT 1 FROM credit_card_batches WHERE dgt_id=? AND status IN ('SETTLED','RECONCILED'))",Boolean.class,store));}
 @GetMapping @Transactional(readOnly=true)
 public Object get(@PathVariable String store,@RequestParam(required=false) LocalDate start,@RequestParam(required=false) LocalDate end){access(store);var tz=zone(store);String latest=a.db.queryForObject("SELECT max(day)::text FROM (SELECT (sale_datetime AT TIME ZONE ?)::date AS day FROM sales WHERE store_id=? UNION ALL SELECT business_date FROM credit_card_batches WHERE dgt_id=?) s",String.class,tz.getId(),store,store);LocalDate last=latest==null?LocalDate.now(tz):LocalDate.parse(latest);if(end==null)end=last;if(start==null)start=end.withDayOfMonth(1);day(store,start);day(store,end);if(start.isAfter(end)||java.time.temporal.ChronoUnit.DAYS.between(start,end)>365)throw bad("Choose a range of up to 366 days");var result=new LinkedHashMap<String,Object>();var settings=settings(store);result.put("settings",settings);result.put("settingsLocked",locked(store,settings));result.put("today",LocalDate.now(tz));result.put("latest",last);result.put("start",start);result.put("end",end);result.put("processors",a.db.queryForList("SELECT *,xmin::text AS version FROM credit_card_processors WHERE dgt_id=? ORDER BY lower(processor_name),processor_id",store));result.put("batches",a.db.queryForList("SELECT b.*,b.xmin::text AS version,p.processor_name FROM credit_card_batches b JOIN credit_card_processors p ON p.processor_id=b.processor_id AND p.dgt_id=b.dgt_id WHERE b.dgt_id=? AND b.business_date BETWEEN ? AND ? ORDER BY b.business_date DESC,b.batch_id DESC",store,start,end));result.put("audit",a.db.queryForList("SELECT e.event_id,e.created_at,e.event_type,e.target_id,e.changes::text AS changes,u.first_name||' '||u.last_name AS actor FROM access_audit_events e LEFT JOIN users u ON u.user_id=e.actor_user_id WHERE e.dgt_id=? AND e.event_type LIKE 'CREDIT_CARD_%' ORDER BY e.event_id DESC LIMIT 200",store));return result;}
 public record SettingsSave(String version,Map<String,Object> values){}
 @PutMapping("/settings") @Transactional
 public Object saveSettings(@PathVariable String store,@RequestBody SettingsSave in){lock(store);var old=settings(store);version(old,in.version());if(locked(store,old))throw conflict("Settings are locked after the first settlement");if(in.values()==null)throw bad("Settings are required");var allowed=new HashSet<>(NUMBERS);allowed.addAll(FLAGS);if(!allowed.equals(in.values().keySet()))throw bad("Supply the supported settings fields");for(String k:NUMBERS)if(!(in.values().get(k) instanceof Number))throw bad("Invalid number for "+k);for(String k:FLAGS)if(!(in.values().get(k) instanceof Boolean))throw bad("Invalid setting "+k);rate(in.values().get("default_fee_percent"));rate(in.values().get("fee_difference_percent"));money(n(in.values().get("per_transaction_fee")),false);money(n(in.values().get("deposit_tolerance")),false);
 a.db.update("INSERT INTO credit_card_settings(dgt_id,updated_by) VALUES (?,?) ON CONFLICT(dgt_id) DO NOTHING",store,a.user());for(String k:allowed)a.db.update("UPDATE credit_card_settings SET "+k+"=?,updated_by=?,updated_at=clock_timestamp() WHERE dgt_id=?",FLAGS.contains(k)?in.values().get(k):n(in.values().get(k)),a.user(),store);var saved=settings(store);audit(store,"SETTINGS",store,old,saved);return saved;}
 public record ProcessorSave(String version,String name,boolean active,String frequency,Integer delayDays,String destination,String destinationLabel){}
 @PostMapping("/processors") @Transactional public Object addProcessor(@PathVariable String store,@RequestBody ProcessorSave in){return processor(store,null,in);}
 @PutMapping("/processors/{id}") @Transactional public Object editProcessor(@PathVariable String store,@PathVariable long id,@RequestBody ProcessorSave in){return processor(store,id,in);}
 private Object processor(String store,Long id,ProcessorSave in){lock(store);if(locked(store,settings(store)))throw conflict("Processor settings are locked after the first settlement");String name=str(in.name(),120,true),label=str(in.destinationLabel(),160,true);if(in.frequency()==null||!Set.of("DAILY","WEEKLY","MONTHLY").contains(in.frequency())||in.delayDays()==null||in.delayDays()<0||in.delayDays()>90||in.destination()==null||!Set.of("BANK","JOBBER").contains(in.destination()))throw bad("Enter a valid processor schedule and settlement destination");Map<String,Object> old=Map.of();if(id!=null){old=processorRow(store,id);version(old,in.version());}if(Boolean.TRUE.equals(a.db.queryForObject("SELECT EXISTS(SELECT 1 FROM credit_card_processors WHERE dgt_id=? AND lower(trim(processor_name))=lower(?) AND processor_id<>?)",Boolean.class,store,name,id==null?0:id)))throw conflict("A processor with this name already exists in this store");if(id==null)id=a.db.queryForObject("INSERT INTO credit_card_processors(dgt_id,processor_name,is_active,settlement_frequency,deposit_delay_days,settlement_destination,destination_label,created_by) VALUES (?,?,?,?,?,?,?,?) RETURNING processor_id",Long.class,store,name,in.active(),in.frequency(),in.delayDays(),in.destination(),label,a.user());else a.db.update("UPDATE credit_card_processors SET processor_name=?,is_active=?,settlement_frequency=?,deposit_delay_days=?,settlement_destination=?,destination_label=?,updated_at=clock_timestamp() WHERE processor_id=? AND dgt_id=?",name,in.active(),in.frequency(),in.delayDays(),in.destination(),label,id,store);var saved=processorRow(store,id);audit(store,"PROCESSOR",id,old,saved);return saved;}
 private Map<String,Object> processorRow(String store,long id){var rows=a.db.queryForList("SELECT *,xmin::text AS version FROM credit_card_processors WHERE processor_id=? AND dgt_id=?",id,store);if(rows.isEmpty())throw new ResponseStatusException(HttpStatus.NOT_FOUND,"Processor not found");return rows.getFirst();}
 private static final String PAYMENT_SQL="""
 SELECT p.sale_payment_id,s.sale_id,s.receipt_no,s.sale_datetime,t.tender_code,
  CASE WHEN s.transaction_type='SALE' THEN abs(p.payment_amount) ELSE -abs(p.payment_amount) END amount,
  s.transaction_type,p.xmin::text||':'||s.xmin::text AS version
 FROM sale_payments p JOIN sales s USING(sale_id) JOIN tender_types t USING(tender_type_id)
 WHERE s.store_id=? AND s.sale_datetime>=? AND s.sale_datetime<?
  AND t.tender_code IN ('CREDIT_CARD','DEBIT_CARD') AND p.payment_status IN ('COMPLETED','REFUNDED')
  AND ((s.transaction_type='SALE' AND s.sale_status='COMPLETED') OR
    (s.transaction_type IN ('REFUND','RETURN') AND s.sale_status IN ('COMPLETED','REFUNDED')))
  AND NOT EXISTS(SELECT 1 FROM credit_card_batch_payments bp WHERE bp.sale_payment_id=p.sale_payment_id)
 ORDER BY p.sale_payment_id
 """;
 private List<Map<String,Object>> payments(String store,LocalDate date,boolean lock){day(store,date);var tz=zone(store);return a.db.queryForList(PAYMENT_SQL+(lock?" FOR UPDATE OF p,s":""),store,Timestamp.from(date.atStartOfDay(tz).toInstant()),Timestamp.from(date.plusDays(1).atStartOfDay(tz).toInstant()));}
 @GetMapping("/payments") @Transactional(readOnly=true) public Object payments(@PathVariable String store,@RequestParam LocalDate date){access(store);return payments(store,date,false);}
 public record Create(long processorId,String reference,LocalDate date,UUID requestKey,Map<Long,String> payments){}
 @PostMapping("/batches") @Transactional
 public Object create(@PathVariable String store,@RequestBody Create in){lock(store);day(store,in.date());String ref=str(in.reference(),100,true);if(in.requestKey()==null||in.payments()==null||in.payments().isEmpty()||in.payments().size()>2000)throw bad("Select between 1 and 2000 card payments");var prior=a.db.queryForList("SELECT *,xmin::text AS version FROM credit_card_batches WHERE dgt_id=? AND request_key=?",store,in.requestKey());if(!prior.isEmpty()){var row=prior.getFirst();var ids=new HashSet<>(a.db.queryForList("SELECT sale_payment_id FROM credit_card_batch_payments WHERE batch_id=?",Long.class,row.get("batch_id")));if(!ids.equals(in.payments().keySet())||!Objects.equals(row.get("batch_reference"),ref)||((Number)row.get("processor_id")).longValue()!=in.processorId()||!row.get("business_date").toString().equals(in.date().toString()))throw conflict("Request key already used with different batch details");return row;}
 var processor=processorRow(store,in.processorId());if(!Boolean.TRUE.equals(processor.get("is_active")))throw bad("Choose an active processor");if(Boolean.TRUE.equals(a.db.queryForObject("SELECT EXISTS(SELECT 1 FROM credit_card_batches WHERE dgt_id=? AND processor_id=? AND batch_reference=?)",Boolean.class,store,in.processorId(),ref)))throw conflict("Batch reference already exists for this processor");var chosen=payments(store,in.date(),true).stream().filter(p->in.payments().containsKey(((Number)p.get("sale_payment_id")).longValue())).toList();if(chosen.size()!=in.payments().size())throw conflict("Some payments are unavailable or already assigned to a batch");for(var p:chosen)if(!Objects.equals(p.get("version"),in.payments().get(((Number)p.get("sale_payment_id")).longValue())))throw conflict("Payment changed; reload available payments");BigDecimal sales=BigDecimal.ZERO,base=BigDecimal.ZERO;int count=0;for(var p:chosen){sales=sales.add(n(p.get("amount")));if("SALE".equals(p.get("transaction_type"))){base=base.add(n(p.get("amount")));count++;}}var settings=settings(store);BigDecimal rate=n(settings.get("default_fee_percent")),swipe=n(settings.get("per_transaction_fee")),expected=base.multiply(rate).movePointLeft(2).add(swipe.multiply(BigDecimal.valueOf(count))).setScale(2,RoundingMode.HALF_UP);money(sales,true);money(base,false);money(expected,false);
 long id=a.db.queryForObject("""
 INSERT INTO credit_card_batches(dgt_id,processor_id,batch_reference,business_date,pos_sales,transaction_count,fee_base,configured_fee_percent,per_transaction_fee,expected_fee,settlement_destination,destination_label,created_by,request_key)
 VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?) RETURNING batch_id
 """,Long.class,store,in.processorId(),ref,in.date(),sales,count,base,rate,swipe,expected,processor.get("settlement_destination"),processor.get("destination_label"),a.user(),in.requestKey());for(var p:chosen)a.db.update("INSERT INTO credit_card_batch_payments(batch_id,sale_payment_id,payment_amount_snapshot) VALUES (?,?,?)",id,p.get("sale_payment_id"),p.get("amount"));var saved=batch(store,id);audit(store,"BATCH_CREATED",id,Map.of(),saved);return saved;}
 private Map<String,Object> batch(String store,long id){var rows=a.db.queryForList("SELECT *,xmin::text AS version FROM credit_card_batches WHERE dgt_id=? AND batch_id=?",store,id);if(rows.isEmpty())throw new ResponseStatusException(HttpStatus.NOT_FOUND,"Batch not found");return rows.getFirst();}
 public record Fee(String version,BigDecimal actualFee,String reason,String notes){}
 @PutMapping("/batches/{id}/fee") @Transactional
 public Object fee(@PathVariable String store,@PathVariable long id,@RequestBody Fee in){lock(store);var old=batch(store,id);version(old,in.version());if("RECONCILED".equals(old.get("status")))throw conflict("Reconciled batches are locked");money(in.actualFee(),false);String reason=str(in.reason(),1000,false),notes=str(in.notes(),2000,false);BigDecimal tolerance=n(old.get("fee_base")).multiply(n(settings(store).get("fee_difference_percent"))).movePointLeft(2);if(in.actualFee().subtract(n(old.get("expected_fee"))).abs().compareTo(tolerance)>0&&reason.isEmpty())throw bad("A reason is required when the fee difference exceeds the configured tolerance");a.db.update("UPDATE credit_card_batches SET actual_fee=?,fee_reason=?,notes=?,fee_reviewed_by=?,variance_reviewed_by=NULL,variance_review_note=NULL,updated_at=clock_timestamp() WHERE batch_id=?",in.actualFee(),reason,notes,a.user(),id);var saved=batch(store,id);audit(store,"FEE_UPDATED",id,old,saved);return saved;}
 public record Transition(String version,String action,BigDecimal processorSales,BigDecimal chargebacks,String chargebackReason,BigDecimal receivedAmount,LocalDate settlementDate,String reference,String reviewNote){}
 @PostMapping("/batches/{id}/transition") @Transactional
 public Object transition(@PathVariable String store,@PathVariable long id,@RequestBody Transition in){lock(store);var old=batch(store,id);version(old,in.version());String status=old.get("status").toString();var settings=settings(store);
 if("SUBMIT".equals(in.action())){if(!status.equals("OPEN"))throw conflict("Only open batches can be submitted");money(in.processorSales(),true);money(in.chargebacks(),false);String reason=str(in.chargebackReason(),1000,false);if(in.chargebacks().signum()>0){if(!Boolean.TRUE.equals(settings.get("enable_chargebacks")))throw bad("Chargeback tracking is disabled in settings");if(Boolean.TRUE.equals(settings.get("require_chargeback_reason"))&&reason.isEmpty())throw bad("Enter a chargeback reason");}a.db.update("UPDATE credit_card_batches SET processor_sales=?,chargebacks=?,chargeback_reason=?,status='SUBMITTED',updated_at=clock_timestamp() WHERE batch_id=?",in.processorSales(),in.chargebacks(),reason,id);}
 else if("SETTLE".equals(in.action())){if(!status.equals("SUBMITTED"))throw conflict("Only submitted batches can be settled");if(old.get("actual_fee")==null)throw bad("Record the actual batch fee before settlement");money(in.receivedAmount(),true);day(store,in.settlementDate());if(in.settlementDate().isBefore(LocalDate.parse(old.get("business_date").toString())))throw bad("Settlement date cannot precede the business date");String ref=str(in.reference(),160,true),note=str(in.reviewNote(),1000,false);boolean review=needsReview(old,in.receivedAmount(),settings);if(review&&note.isEmpty())throw bad("Enter a variance review note before confirming settlement");a.db.update("UPDATE credit_card_batches SET received_amount=?,settlement_date=?,settlement_reference=?,variance_review_note=?,variance_reviewed_by=?,settled_by=?,status='SETTLED',updated_at=clock_timestamp() WHERE batch_id=?",in.receivedAmount(),in.settlementDate(),ref,note,review?a.user():null,a.user(),id);}
 else if("RECONCILE".equals(in.action())){if(!status.equals("SETTLED"))throw conflict("Only settled batches can be reconciled");if(Boolean.TRUE.equals(settings.get("require_fee_review"))&&old.get("fee_reviewed_by")==null)throw bad("Review the actual batch fee first");String note=str(in.reviewNote(),1000,false);boolean review=needsReview(old,n(old.get("received_amount")),settings);if(review&&old.get("variance_reviewed_by")==null&&note.isEmpty())throw bad("Enter a variance review note");a.db.update("UPDATE credit_card_batches SET status='RECONCILED',reconciled_by=?,variance_review_note=CASE WHEN ?<>'' THEN ? ELSE variance_review_note END,variance_reviewed_by=CASE WHEN ?<>'' THEN ? ELSE variance_reviewed_by END,updated_at=clock_timestamp() WHERE batch_id=?",a.user(),note,note,note,a.user(),id);}
 else throw bad("Unknown batch action");var saved=batch(store,id);audit(store,"BATCH_"+in.action(),id,old,saved);return saved;}
 private boolean needsReview(Map<String,Object> b,BigDecimal received,Map<String,Object> settings){if(!Boolean.TRUE.equals(settings.get("require_variance_review")))return false;BigDecimal tolerance=n(settings.get("deposit_tolerance")),net=n(b.get("processor_sales")).subtract(n(b.get("actual_fee"))).subtract(n(b.get("chargebacks")));return received.subtract(net).abs().compareTo(tolerance)>0||n(b.get("processor_sales")).subtract(n(b.get("pos_sales"))).abs().compareTo(tolerance)>0;}
}
