import {useState} from 'react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Label} from '@/components/ui/label';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription,DialogFooter} from '@/components/ui/dialog';
import {useGasSettings} from './gasSettingsState';
export function FuelGradeSetup(){const {grades,addGrade,editable}=useGasSettings();const [open,setOpen]=useState(false),[name,setName]=useState(''),[type,setType]=useState(''),[octane,setOctane]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const save=async()=>{setBusy(true);setError('');try{if(!name.trim()||!type.trim()||octane.trim()===''||!Number.isFinite(Number(octane)))throw Error('Enter the grade name, fuel type and octane.');await addGrade({name,type,octane:Number(octane)});setOpen(false);setName('');setType('');setOctane('');}catch(e){setError(e instanceof Error?e.message:'Could not save grade');}finally{setBusy(false);}};
 return <div className="mt-3 space-y-2"><div className="flex justify-between items-center"><Label className="text-xs">Fuel Grades</Label><Button size="sm" variant="outline" disabled={!editable} onClick={()=>{setError('');setOpen(true);}}>Add Fuel Grade</Button></div><p className="text-xs text-muted-foreground">{grades.length?grades.map(g=>`${g.name} (${g.type}${g.octane>0?`, ${g.octane} octane`:''})`).join(' · '):'No fuel grades configured yet.'}</p><p className="text-[10px] text-muted-foreground">Grade definitions are shared. Each store chooses its own tank assignments.</p>
 <Dialog open={open} onOpenChange={v=>!busy&&setOpen(v)}><DialogContent><DialogHeader><DialogTitle>Add Fuel Grade</DialogTitle><DialogDescription>Save a grade definition for tank selection. Existing grades are preserved.</DialogDescription></DialogHeader>{error&&<p role="alert" className="text-destructive">{error}</p>}<Label htmlFor="gas-grade-name">Grade name</Label><Input id="gas-grade-name" value={name} onChange={e=>setName(e.target.value)} placeholder="e.g. Regular"/><Label htmlFor="gas-grade-type">Fuel type</Label><Input id="gas-grade-type" value={type} onChange={e=>setType(e.target.value)} placeholder="e.g. Gasoline or Diesel"/><Label htmlFor="gas-grade-octane">Octane (0 if not applicable)</Label><Input id="gas-grade-octane" type="number" min="0" step="0.01" value={octane} onChange={e=>setOctane(e.target.value)}/><DialogFooter><Button variant="outline" disabled={busy} onClick={()=>setOpen(false)}>Cancel</Button><Button disabled={busy} onClick={save}>{busy?'Saving…':'Save Fuel Grade'}</Button></DialogFooter></DialogContent></Dialog></div>;
}
