import {Card,CardContent,CardHeader,CardTitle} from '@/components/ui/card';
import {Table,TableBody,TableCell,TableHead,TableHeader,TableRow} from '@/components/ui/table';
import {Badge} from '@/components/ui/badge';
import {Input} from '@/components/ui/input';
import {Button} from '@/components/ui/button';
import {Lock,Plus} from 'lucide-react';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
import {useGasSettings,type GasTank} from './gasSettingsState';
export const TankConfiguration=()=>{
 const {tanks,setTanks,grades,editable}=useGasSettings();
 const update=(key:string,field:keyof GasTank,value:string)=>setTanks(tanks.map(t=>t.key===key?{...t,[field]:value}:t));
 const addTank=()=>setTanks([...tanks,{key:crypto.randomUUID(),id:null,version:'0',number:'',name:'',gradeId:'',capacity:'',safeFill:'',lowLevel:'',prepaidTax:'',taxRate:'',ustFees:'',posMapping:'',capacityLocked:false,gradeLocked:false,hasReadings:false}]);
 const numeric=(t:GasTank,key:'capacity'|'safeFill'|'lowLevel'|'prepaidTax'|'taxRate'|'ustFees',locked=false)=><Input aria-label={`${key} ${t.number||'new tank'}`} type="number" min="0" step={['prepaidTax','taxRate','ustFees'].includes(key)?'0.0001':'0.01'} value={t[key]} disabled={!editable||locked} className="h-7 w-24 text-xs text-right ml-auto" onChange={e=>update(t.key,key,e.target.value)}/>;
 return <Card><CardHeader className="pb-3 flex flex-row items-center justify-between"><div><CardTitle className="text-sm font-semibold">Tank Configuration</CardTitle><p className="text-xs text-muted-foreground">Capacity and assigned fuel type lock once saved. Safe-fill capacity locks when readings exist.</p></div><Button variant="outline" size="sm" className="text-xs gap-1.5" disabled={!editable||grades.length===0} onClick={addTank}><Plus className="h-3.5 w-3.5"/>Add Tank</Button></CardHeader><CardContent className="p-0"><Table><TableHeader><TableRow>{['Tank ID','Name','Fuel Type','Capacity (gal)','Safe Fill (gal)','Low-Level %','Pre-Paid Tax ($/gal)','Tax Rate ($/gal)','UST Fees ($/gal)','POS Mapping','Status'].map(h=><TableHead className="text-xs" key={h}>{h}</TableHead>)}</TableRow></TableHeader><TableBody>
 {tanks.length===0&&<TableRow><TableCell colSpan={11} className="text-xs text-muted-foreground py-6">No tanks configured for this store. {grades.length?'Use Edit Settings, then Add Tank.':'Add a fuel grade first.'}</TableCell></TableRow>}
 {tanks.map(t=><TableRow key={t.key} className="text-xs"><TableCell>{t.id?t.number:<Input aria-label="New tank number" disabled={!editable} value={t.number} className="h-7 w-24 text-xs" onChange={e=>update(t.key,'number',e.target.value)}/>}</TableCell><TableCell><Input aria-label={`Tank name ${t.number||'new tank'}`} disabled={!editable} value={t.name} className="h-7 w-24 text-xs" onChange={e=>update(t.key,'name',e.target.value)}/></TableCell><TableCell>{t.gradeLocked?<span>{grades.find(g=>g.id===t.gradeId)?.name??'Historical assignment'}</span>:<Select disabled={!editable} value={t.gradeId} onValueChange={v=>update(t.key,'gradeId',v)}><SelectTrigger aria-label={`Fuel grade ${t.number||'new tank'}`} className="h-7 w-28 text-xs"><SelectValue placeholder="Choose grade"/></SelectTrigger><SelectContent>{grades.map(g=><SelectItem key={g.id} value={g.id}>{g.name}</SelectItem>)}</SelectContent></Select>}</TableCell><TableCell>{t.capacityLocked?<span className="flex gap-1 items-center justify-end">{Number(t.capacity).toLocaleString()}<Lock className="h-3 w-3"/></span>:numeric(t,'capacity')}</TableCell><TableCell>{numeric(t,'safeFill',t.hasReadings)}</TableCell><TableCell>{numeric(t,'lowLevel')}</TableCell><TableCell>{numeric(t,'prepaidTax')}</TableCell><TableCell>{numeric(t,'taxRate')}</TableCell><TableCell>{numeric(t,'ustFees')}</TableCell><TableCell><Input aria-label={`POS mapping ${t.number||'new tank'}`} disabled={!editable} value={t.posMapping} className="h-7 w-28 text-xs" onChange={e=>update(t.key,'posMapping',e.target.value)}/></TableCell><TableCell><Badge variant="secondary" className="text-[10px]">{t.id?'Locked':'New'}</Badge>{!t.id&&<Button size="sm" variant="ghost" disabled={!editable} onClick={()=>setTanks(tanks.filter(row=>row.key!==t.key))}>Remove</Button>}</TableCell></TableRow>)}
 </TableBody></Table></CardContent></Card>;
};
