// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { brokeredPreviewStorage } from './previewAuthStorage';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;


function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith('sb_publishable_') || value.startsWith('sb_secret_');
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== 'undefined' && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    // New Supabase API keys are opaque strings, not bearer JWTs.
    if (isNewSupabaseApiKey(supabaseKey) && headers.get('Authorization') === `Bearer ${supabaseKey}`) {
      headers.delete('Authorization');
    }

    headers.set('apikey', supabaseKey);
    return fetch(input, { ...init, headers });
  };
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

const legacyClient = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  global: {
    // The Spring-backed app has no scoped Supabase identity. Unfinished layouts
    // must not read or write another data source when mounted by an admin.
    fetch: async () => new Response(JSON.stringify({message:"This feature is not connected to DGT yet"}), {status:503,headers:{"Content-Type":"application/json"}}),
  },
  auth: {
    storage: brokeredPreviewStorage(),
    persistSession: false,
    autoRefreshToken: false,
  }
});

// Prevent legacy layout hooks from opening realtime connections as well.
const offlineChannel = new Proxy({}, {get:(_target,key)=>{
 if(key==='unsubscribe')return async ()=>'ok';
 if(key==='send')return async ()=>'error';
 return ()=>offlineChannel;
}});
export const supabase = new Proxy(legacyClient, {get(target,key){
 if(key==='channel')return ()=>offlineChannel;
 if(key==='removeChannel'||key==='removeAllChannels')return async ()=>'ok';
 const value=Reflect.get(target,key);
 return typeof value==='function'?value.bind(target):value;
}});
