import {useState} from 'react';
import {useQuery,useQueryClient} from '@tanstack/react-query';
import {request} from '@/lib/backend';
import {Card,CardHeader,CardTitle,CardContent} from '@/components/ui/card';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Label} from '@/components/ui/label';
import {Switch} from '@/components/ui/switch';
import {Badge} from '@/components/ui/badge';
import {Table,TableHeader,TableHead,TableBody,TableRow,TableCell} from '@/components/ui/table';
type Settings={priceChangeAlerts:boolean;alertThreshold?:number|null;approvalRequired:boolean;approvalThreshold?:number|null;autoPick:boolean;fallback:boolean;considerLeadTime:boolean;version:string};
type History={id:string;item:string;vendor:string;oldCost:number|null;newCost:number|null;change:number|null;effectiveDate:string|null;changedBy:string|null;source:string|null;difference:number|null;timestamp:string|null;invoiceNumber:string|null;previousInvoice:string|null;previousInvoiceDate:string|null;unit:string|null;casePack:number|null};
type CostItem={id:number;item:string;vendor:string;cost:number;unit:string;version:string};
export function VendorPricing({storeId}:{storeId:string}){
 const path=`/access/stores/${encodeURIComponent(storeId)}/vendors/pricing`,client=useQueryClient();
 const query=useQuery({queryKey:['vendor-pricing',storeId],queryFn:async()=>{await request(path+'/invoice-costs',{method:'POST'});return request<{settings:Settings;configured:boolean;history:History[]}>(path);}});
 const [draft,setDraft]=useState<Settings|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const items=useQuery({queryKey:['vendor-cost-items',storeId],queryFn:()=>request<CostItem[]>(path+'/items')});
 const [editingCost,setEditingCost]=useState(false),[selected,setSelected]=useState(''),[newCost,setNewCost]=useState('');
 async function saveCost(){const item=items.data?.find(i=>String(i.id)===selected);if(!item)return;setBusy(true);setError('');try{await request(path+`/items/${item.id}/cost`,{method:'PUT',headers:{'If-Match':item.version},body:JSON.stringify({cost:Number(newCost)})});setEditingCost(false);await Promise.all([client.invalidateQueries({queryKey:['vendor-cost-items',storeId]}),client.invalidateQueries({queryKey:['vendor-pricing',storeId]}),client.invalidateQueries({queryKey:['vendor-audit',storeId]}),client.invalidateQueries({queryKey:['vendor-items',storeId]})]);}catch(e){setError(e instanceof Error?e.message:'Could not update cost');}finally{setBusy(false);}}
 const current=draft??query.data?.settings;
 const change=(key:keyof Settings,value:boolean|number|null)=>setDraft(old=>old?{...old,[key]:value}:old);
 async function save(){if(!draft)return;setBusy(true);setError('');try{const result=await request<{settings:Settings;configured:boolean;history:History[]}>(path,{method:'PUT',headers:{'If-Match':draft.version},body:JSON.stringify(draft)});client.setQueryData(['vendor-pricing',storeId],result);await client.invalidateQueries({queryKey:['vendor-audit',storeId]});setDraft(null);}catch(e){setError(e instanceof Error?e.message:'Could not save preferences');}finally{setBusy(false);}}
 const toggle=(key:'priceChangeAlerts'|'approvalRequired'|'autoPick'|'fallback'|'considerLeadTime',label:string,description:string)=><div className="flex items-center justify-between"><div><p className="font-medium text-sm">{label}</p><p className="text-xs text-muted-foreground">{description}</p></div><Switch aria-label={label} disabled={!draft||busy} checked={current?.[key]??false} onCheckedChange={v=>change(key,v)}/></div>;
 const threshold=(key:'alertThreshold'|'approvalThreshold',label:string)=><div className="space-y-2"><Label htmlFor={key}>{label}</Label><Input id={key} disabled={!draft||busy||!current?.[key==='alertThreshold'?'priceChangeAlerts':'approvalRequired']} type="number" min="0" step="0.01" className="w-24" value={current?.[key]??''} onChange={e=>change(key,e.target.value===''?null:Number(e.target.value))}/></div>;
 return <div className="space-y-4">{query.isPending&&<p>Loading pricing…</p>}{query.error&&<p role="alert">{query.error.message}</p>}{error&&<p role="alert">{error}</p>}
 <div className="flex justify-end gap-2">{!draft?<Button variant="outline" disabled={!query.data} onClick={()=>{setDraft({...query.data!.settings});setError('');}}>Edit</Button>:<><Button disabled={busy} onClick={save}>{busy?'Saving…':'Save Preferences'}</Button><Button disabled={busy} variant="outline" onClick={()=>{setDraft(null);setError('');void query.refetch();}}>Cancel</Button></>}</div>
 <div className="grid grid-cols-2 gap-4"><Card><CardHeader><CardTitle className="text-lg">Pricing Controls</CardTitle></CardHeader><CardContent className="space-y-4">{toggle('priceChangeAlerts','Price Change Alerts','Notify when cost changes exceed threshold')}{threshold('alertThreshold','Alert Threshold (%)')}{toggle('approvalRequired','Approval Required','Require approval for cost changes beyond threshold')}{threshold('approvalThreshold','Approval Threshold (%)')}</CardContent></Card>
 <Card><CardHeader><CardTitle className="text-lg">Preferred Vendor Rules</CardTitle></CardHeader><CardContent className="space-y-4">{toggle('autoPick','Auto-pick in Order Guide','Automatically select preferred vendor')}{toggle('fallback','Use Fallback Vendor','Switch to alternate if preferred is unavailable')}{toggle('considerLeadTime','Consider Lead Time','Factor lead time into vendor selection')}</CardContent></Card></div>
 <p className="text-sm text-muted-foreground">{query.data?.configured?'Preferences saved for this store.':'No preferences saved for this store yet.'} Automatic alerts, cost approvals and Order Guide selection are not connected yet.</p>
 <Card><CardHeader><div className="flex justify-between items-center"><CardTitle className="text-lg">Cost Change History</CardTitle><Button variant="outline" onClick={()=>{setEditingCost(true);setSelected('');setNewCost('');}}>Edit Cost</Button></div></CardHeader>
 {editingCost&&<CardContent className="space-y-3"><Label htmlFor="cost-item">Item / Vendor</Label><select id="cost-item" className="w-full border rounded-md p-2" disabled={busy} value={selected} onChange={e=>{setSelected(e.target.value);setNewCost('');}}><option value="">Choose linked item</option>{items.data?.map(i=><option key={i.id} value={i.id}>{i.item} — {i.vendor} (${i.cost.toFixed(2)} / {i.unit})</option>)}</select>{items.error&&<p role="alert">{items.error.message}</p>}<Label htmlFor="new-cost">New Cost (same unit as selected item)</Label><Input id="new-cost" type="number" min="0" step="0.01" disabled={busy} value={newCost} onChange={e=>setNewCost(e.target.value)}/><div className="flex gap-2"><Button disabled={busy||!selected||newCost===''||!Number.isFinite(Number(newCost))||Number(newCost)<0} onClick={saveCost}>Save Cost</Button><Button variant="outline" disabled={busy} onClick={()=>setEditingCost(false)}>Cancel</Button></div></CardContent>}<Table><TableHeader><TableRow>{['Item','Vendor','Old Cost','New Cost','Difference','Change','Effective Date','Changed By','Source'].map(h=><TableHead key={h}>{h}</TableHead>)}</TableRow></TableHeader><TableBody>{query.data?.history.map(h=><TableRow key={h.id}><TableCell>{h.item}</TableCell><TableCell>{h.vendor}</TableCell><TableCell>{h.oldCost==null?'':`$${h.oldCost.toFixed(2)}`}</TableCell><TableCell>{h.newCost==null?'':`$${h.newCost.toFixed(2)}`}</TableCell><TableCell>{h.difference==null?'':`${h.difference>0?'+':''}$${h.difference.toFixed(2)}`}</TableCell><TableCell>{h.change!=null&&<Badge className={h.change>0?'bg-red-100 text-red-800':'bg-green-100 text-green-800'}>{h.change>0?'+':''}{h.change.toFixed(1)}%</Badge>}</TableCell><TableCell>{h.effectiveDate}</TableCell><TableCell>{h.changedBy}</TableCell><TableCell>{h.source?.startsWith('INVOICE:')?`Invoice ${h.invoiceNumber??h.source.split(':')[1]} ← ${h.previousInvoice??h.source.split(':')[2]} (${h.previousInvoiceDate??''}), ${h.unit??''}${h.unit==='CASE'?` / ${h.casePack} items`: ''}`:h.source==='MANUAL:CATALOG'?'Manual — Items (per item)':h.source}</TableCell></TableRow>)}{query.data?.history.length===0&&<TableRow><TableCell colSpan={9} className="text-center py-8 text-muted-foreground">No cost changes recorded for this store.</TableCell></TableRow>}</TableBody></Table><p className="p-4 text-xs text-muted-foreground">Latest 200 cost changes. Approved invoices are checked when this tab loads. Invoice comparisons use gross cost for the same item/case size and do not change the current vendor cost.</p></Card></div>;
}
