import {useEffect,useRef,useState} from 'react';
import {X,Plus,Trash2} from 'lucide-react';
import {request} from '@/lib/backend';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Textarea} from '@/components/ui/textarea';
import {Drawer,DrawerContent,DrawerHeader,DrawerTitle,DrawerFooter} from '@/components/ui/drawer';
import {Table,TableHead,TableHeader,TableRow,TableBody,TableCell} from '@/components/ui/table';
import {type AdjustmentData,type AdjustmentRecord,reasons} from './gasAdjustmentData';
import {toast} from 'sonner';
type Row={key:string;tankId:string;actual:string;reason:string};
const fresh=():Row=>({key:crypto.randomUUID(),tankId:'',actual:'',reason:''});
export const NewAdjustmentDrawer=({open,onOpenChange,path,record,onSaved}:{open:boolean;onOpenChange:(v:boolean)=>void;path:string;record:AdjustmentRecord|null;onSaved:()=>void})=>{
 const [data,setData]=useState<AdjustmentData|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[notes,setNotes]=useState(record?.notes??''),[rows,setRows]=useState<Row[]>(record?record.lines.map(l=>({key:crypto.randomUUID(),tankId:l.tankId,actual:String(l.actualGallons),reason:l.reason})):[fresh()]);
 const [initial,setInitial]=useState<Record<string,string>>({});const identity=useRef({payload:'',key:crypto.randomUUID()});
 const load=()=>request<AdjustmentData>(path).then(setData).catch(e=>setError(e.message));
 useEffect(()=>{let active=true;request<AdjustmentData>(path).then(d=>{if(active)setData(d);}).catch(e=>{if(active)setError(e.message);});return()=>{active=false;};},[path]);
 const change=(key:string,field:keyof Row,value:string)=>setRows(prev=>prev.map(r=>r.key===key?{...r,[field]:value,...(field==='tankId'?{actual:''}:{})}:r));
 const save=async(submit:boolean)=>{
  if(!data||busy)return;setError('');
  const lines=[];for(const r of rows){const t=data.tanks.find(t=>t.id===r.tankId);if(!t||t.systemGallons===null||!t.readingId||!t.gradeId||r.actual.trim()===''||!Number.isFinite(Number(r.actual))||Number(r.actual)<0||!r.reason){setError('Select a configured tank, actual gallons and reason for every row.');return;}lines.push({tankId:t.id,gradeId:t.gradeId,systemGallons:t.systemGallons,actualGallons:Number(r.actual),readingId:t.readingId,movementId:t.movementId,reason:r.reason});}
  const payload=JSON.stringify({date:data.today,notes,lines,submit});if(identity.current.payload!==payload)identity.current={payload,key:crypto.randomUUID()};setBusy(true);
  try{const result=await request<AdjustmentRecord>(path+(record?`/${record.id}`:''),{method:record?'PUT':'POST',headers:{'Idempotency-Key':identity.current.key,...(record?{'If-Match':record.version}:{})},body:payload});toast.success(result.status==='POSTED'?'Adjustment approved and gallons recorded.':result.status==='PENDING'?'Adjustment submitted for approval.':'Draft saved.');onSaved();}catch(e){setError((e as Error).message);}finally{setBusy(false);}
 };
 const baseline=async(id:string)=>{const value=initial[id];if(!value?.trim()||!Number.isFinite(Number(value))||Number(value)<0){setError('Enter the currently measured gallons, including zero for an empty tank.');return;}setBusy(true);setError('');try{const d=await request<AdjustmentData>(`${path}/tanks/${id}/initial-reading`,{method:'POST',body:JSON.stringify({gallons:Number(value)})});setData(d);toast.success('Initial measured tank reading recorded.');}catch(e){setError((e as Error).message);}finally{setBusy(false);}};
 const total=rows.reduce((s,r)=>{const t=data?.tanks.find(t=>t.id===r.tankId);return s+(t?.systemGallons!=null&&r.actual!==''?Number(r.actual)-t.systemGallons:0);},0);
 return <Drawer open={open} onOpenChange={v=>{if(!busy)onOpenChange(v);}}><DrawerContent className="max-h-[92vh]"><DrawerHeader className="flex items-center justify-between border-b border-border pb-3"><DrawerTitle className="text-base">{record?`Edit Adjustment ADJ-${record.id}`:'New Adjustment'}</DrawerTitle><Button variant="ghost" size="icon" disabled={busy} aria-label="Close adjustment" onClick={()=>onOpenChange(false)}><X className="h-4 w-4"/></Button></DrawerHeader>
 <div className="p-4 space-y-4 overflow-y-auto">{error&&<p role="alert" className="text-sm text-destructive">{error} {!data&&<Button onClick={load}>Retry</Button>}</p>}{!data?<p>Loading current tank gallons…</p>:<>
 <p className="text-xs">Adjustment Date: {data.today} · Store-local date</p>
 {record&&<p className="text-xs text-muted-foreground">Current system gallons have been refreshed. Confirm the actual gallons before saving again.</p>}
 {!data.tanks.length&&<p>Add tanks and fuel grade assignments in Gas Settings first.</p>}
 {data.tanks.filter(t=>t.systemGallons===null).map(t=><div key={t.id} className="rounded-md border p-3 space-y-2"><p className="text-xs">Tank {t.number}: initial measured reading needed.</p>{data.isAdmin?<div className="flex gap-2 items-center"><Input type="number" min="0" step="0.01" aria-label={`Initial gallons ${t.number}`} placeholder="Currently measured gallons" value={initial[t.id]??''} onChange={e=>setInitial({...initial,[t.id]:e.target.value})} className="max-w-64"/><Button variant="outline" disabled={busy||!t.gradeId} onClick={()=>baseline(t.id)}>Record initial reading</Button></div>:<p className="text-xs text-muted-foreground">Ask an admin to record the initial measured tank gallons.</p>}</div>)}
 <div className="flex items-center justify-between"><p className="text-xs font-semibold">Tank / Grade Adjustments</p><Button variant="outline" size="sm" className="gap-1 text-xs" disabled={busy||rows.length>=data.tanks.length} onClick={()=>setRows([...rows,fresh()])}><Plus className="h-3 w-3"/>Add Tank</Button></div>
 <div className="border border-border rounded-lg overflow-hidden"><Table><TableHeader><TableRow className="bg-muted/30">{['Tank / Grade','System Vol (gal)','Actual Vol (gal)','Adjusted (gal)','Reason',''].map((h,i)=><TableHead key={i} className="text-[10px] font-semibold uppercase tracking-wider h-8">{h}</TableHead>)}</TableRow></TableHeader><TableBody>{rows.map(r=>{const t=data.tanks.find(t=>t.id===r.tankId);const diff=t?.systemGallons!=null&&r.actual!==''?Number(r.actual)-t.systemGallons:null;return <TableRow key={r.key}><TableCell><select aria-label="Tank" className="h-8 border rounded-md bg-background text-xs px-2" disabled={busy} value={r.tankId} onChange={e=>change(r.key,'tankId',e.target.value)}><option value="">Select tank</option>{data.tanks.filter(t=>!rows.some(other=>other.key!==r.key&&other.tankId===t.id)).map(t=><option key={t.id} value={t.id} disabled={!t.gradeId||t.systemGallons===null}>{t.number} · {t.gradeName??'Grade needed'}{t.systemGallons===null?' · Reading needed':''}</option>)}</select></TableCell><TableCell className="text-xs">{t?.systemGallons?.toLocaleString()??'—'}</TableCell><TableCell><Input aria-label="Actual gallons" className="h-8 w-32 text-xs" type="number" min="0" step="0.001" disabled={busy} value={r.actual} onChange={e=>change(r.key,'actual',e.target.value)}/></TableCell><TableCell className={diff!==null&&diff<0?'text-destructive':'text-emerald-600'}>{diff===null?'—':`${diff>0?'+':''}${diff.toLocaleString()}`}</TableCell><TableCell><select aria-label="Adjustment reason" className="h-8 border rounded-md bg-background text-xs px-2" disabled={busy} value={r.reason} onChange={e=>change(r.key,'reason',e.target.value)}><option value="">Select reason</option>{reasons.map(([id,label])=><option key={id} value={id}>{label}</option>)}</select></TableCell><TableCell>{rows.length>1&&<Button aria-label="Remove tank" variant="ghost" size="icon" disabled={busy} onClick={()=>setRows(rows.filter(x=>x.key!==r.key))}><Trash2 className="h-3 w-3"/></Button>}</TableCell></TableRow>;})}<TableRow className="bg-muted/40"><TableCell colSpan={3} className="text-xs font-semibold">Total adjustment</TableCell><TableCell className="font-semibold">{total>0?'+':''}{total.toLocaleString()} gal</TableCell><TableCell colSpan={2}/></TableRow></TableBody></Table></div>
 <label className="block text-xs">Notes<Textarea value={notes} disabled={busy} maxLength={5000} onChange={e=>setNotes(e.target.value)} className="mt-2"/></label>
 <p className="text-xs text-muted-foreground">{data.isAdmin?'Admin submissions are approved and recorded immediately.':'Submitted adjustments wait for an admin or another authorized manager to approve.'} Drafts do not change gallons.</p></>}
 </div><DrawerFooter className="border-t pt-3"><div className="flex gap-2"><Button variant="outline" className="flex-1" disabled={busy||!data?.tanks.length} onClick={()=>save(false)}>Save Draft</Button><Button className="flex-1" disabled={busy||!data?.tanks.length} onClick={()=>save(true)}>{busy?'Saving…':data?.isAdmin?'Approve & Record':'Submit for Approval'}</Button></div></DrawerFooter></DrawerContent></Drawer>;
};
