import {useState} from 'react';
import {useQuery,useQueryClient} from '@tanstack/react-query';
import {request,type StoreRecord} from '@/lib/backend';
import {useStoreAccess} from '@/lib/store-access';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Table,TableHeader,TableRow,TableHead,TableBody,TableCell} from '@/components/ui/table';
import {useToast} from '@/hooks/use-toast';
type Store={dgt_id:string;store_id:string;store_name:string;parent_store_dgt_id:string|null;parent_store_name:string|null;timezone:string;address:string|null};
type Form={parentStoreId:string;storeId:string;storeName:string;legalBusinessName:string;taxId:string;licenseNumber:string;timezone:string;address:string;phone:string;email:string};
const fields:[keyof Form,string,number,boolean][]=[['storeName','Store / DBA name',150,true],['storeId','Store ID (your location code)',50,true],['legalBusinessName','Legal business name',200,true],['taxId','Tax ID',50,true],['licenseNumber','Location license number',100,true],['address','Address',500,true],['phone','Phone (optional)',20,false],['email','Store email (optional)',255,false]];
export function ManageStoresPage({storeId,onSelect,onSetup}:{storeId:string;onSelect:(id:string)=>void;onSetup:(id:string,page:'employees'|'permissions'|'details')=>void}){
 const access=useStoreAccess(storeId),client=useQueryClient(),{toast}=useToast();
 const path=`/access/stores/${encodeURIComponent(storeId)}/manage-stores`;
 const query=useQuery({queryKey:['manage-stores',storeId],queryFn:()=>request<Store[]>(path),enabled:!!storeId&&access.data?.admin===true});
 const [form,setForm]=useState<Form|null>(null),[key,setKey]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const [zones]=useState(()=>{const intl=Intl as typeof Intl&{supportedValuesOf?:(key:string)=>string[]};return [...new Set(['UTC',...(intl.supportedValuesOf?.('timeZone')??['America/New_York','America/Chicago','America/Denver','America/Los_Angeles','America/Phoenix','Pacific/Honolulu'])])];});
 function parentDefaults(id:string){const parent=client.getQueryData<StoreRecord[]>(['backend-stores'])?.find(s=>s.dgt_id===id);return {timezone:parent?.timezone??'America/New_York',legalBusinessName:parent?.legal_business_name??'',taxId:parent?.tax_id??''};}
 function open(){setForm({parentStoreId:storeId,storeId:'',storeName:'',licenseNumber:'',address:'',phone:'',email:'',...parentDefaults(storeId)});setKey(crypto.randomUUID());setError('');}
 function update(name:keyof Form,value:string){setForm(old=>old?{...old,...(name==='parentStoreId'?parentDefaults(value):{}),[name]:value}:old);setKey(crypto.randomUUID());setError('');}
 async function create(event:React.FormEvent){event.preventDefault();if(!form||busy)return;setBusy(true);setError('');try{
  const result=await request<{dgtId:string}>(path,{method:'POST',headers:{'Idempotency-Key':key},body:JSON.stringify(form)});
  await Promise.all([client.invalidateQueries({queryKey:['backend-stores']}),client.invalidateQueries({queryKey:['manage-stores']})]);
  setForm(null);toast({title:'Child store created',description:'Select Assign employees or Permissions to finish setup.'});onSelect(result.dgtId);
 }catch(e){setError(e instanceof Error?e.message:'Could not create store');}finally{setBusy(false);}}
 if(access.isPending)return <p>Loading store access…</p>;
 if(!access.data?.admin)return <p>Only company admins can manage stores.</p>;
 return <div className="space-y-6"><div className="flex items-center justify-between"><div><h1 className="text-2xl font-bold">Manage Stores</h1><p className="text-muted-foreground">Manage your company’s locations with your existing login.</p></div><Button disabled={query.isPending||!!query.error} onClick={open}>Add Child Store</Button></div>
 {query.isPending&&<p>Loading stores…</p>}{query.error&&<p role="alert">{query.error.message} <Button onClick={()=>query.refetch()}>Retry</Button></p>}
 <Table><TableHeader><TableRow><TableHead>Store</TableHead><TableHead>Parent store</TableHead><TableHead>Timezone</TableHead><TableHead>Setup</TableHead></TableRow></TableHeader><TableBody>{query.data?.map(s=><TableRow key={s.dgt_id}><TableCell><button className="font-medium underline" onClick={()=>onSelect(s.dgt_id)}>{s.store_name}{s.dgt_id===storeId?' (selected)':''}</button><p className="text-xs text-muted-foreground">{s.store_id} · {s.dgt_id}</p><p className="text-xs text-muted-foreground">{s.address}</p></TableCell><TableCell>{s.parent_store_name??'No parent store'}</TableCell><TableCell>{s.timezone}</TableCell><TableCell><div className="flex flex-wrap gap-2"><Button variant="outline" size="sm" onClick={()=>onSetup(s.dgt_id,'employees')}>Assign employees</Button><Button variant="outline" size="sm" onClick={()=>onSetup(s.dgt_id,'permissions')}>Permissions</Button><Button variant="outline" size="sm" onClick={()=>onSetup(s.dgt_id,'details')}>Store details</Button></div></TableCell></TableRow>)}</TableBody></Table>
 <Dialog open={!!form} onOpenChange={open=>{if(!open&&!busy)setForm(null);}}><DialogContent className="sm:max-w-2xl max-h-[90vh] overflow-y-auto"><DialogHeader><DialogTitle>Add Child Store</DialogTitle><DialogDescription>The child store starts with a copy of its parent’s role permissions, which you can change independently. Employees and individual permission overrides are not copied.</DialogDescription></DialogHeader>{form&&<form onSubmit={create} className="space-y-4"><label className="block text-sm font-medium">Parent store<select required disabled={busy} className="mt-1 w-full border rounded-md p-2 bg-background" value={form.parentStoreId} onChange={e=>update('parentStoreId',e.target.value)}>{query.data?.map(s=><option key={s.dgt_id} value={s.dgt_id}>{s.store_name} ({s.dgt_id})</option>)}</select></label><div className="grid grid-cols-1 sm:grid-cols-2 gap-4">{fields.map(([name,label,max,required])=><label key={name} className="text-sm font-medium">{label}<Input required={required} maxLength={max} disabled={busy} type={name==='email'?'email':'text'} value={form[name]} onChange={e=>update(name,e.target.value)}/></label>)}</div><label className="block text-sm font-medium">Timezone<select required disabled={busy} className="mt-1 w-full border rounded-md p-2 bg-background" value={form.timezone} onChange={e=>update('timezone',e.target.value)}>{[...new Set([form.timezone,...zones])].map(zone=><option key={zone} value={zone}>{zone}</option>)}</select></label><p className="text-sm text-muted-foreground">A DGT ID is generated automatically. Set business hours in Store details after creation.</p>{error&&<p role="alert" className="text-destructive">{error}</p>}<div className="flex gap-2"><Button type="submit" disabled={busy}>{busy?'Creating…':'Create Store'}</Button><Button type="button" variant="outline" disabled={busy} onClick={()=>setForm(null)}>Cancel</Button></div></form>}</DialogContent></Dialog>
 </div>;
}
