import {useState} from 'react';
import {useQuery} from '@tanstack/react-query';
import {request} from '@/lib/backend';
import {useCards,type Payment,type Batch,fmt,net} from './creditCardData';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription,DialogFooter} from '@/components/ui/dialog';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
export function CreateBatch({onClose}:{onClose:()=>void}){
 const c=useCards(),data=c.q.data!;const [date,setDate]=useState(data.latest),[processor,setProcessor]=useState(''),[reference,setReference]=useState(''),[selected,setSelected]=useState<Record<number,string>>({}),[key]=useState(crypto.randomUUID());
 const q=useQuery({queryKey:['card-payments',c.base,date],queryFn:()=>request<Payment[]>(c.base+'/payments?date='+date)});
 const sum=(q.data??[]).filter(p=>selected[p.sale_payment_id]).reduce((s,p)=>s+Number(p.amount),0);
 return <Dialog open onOpenChange={open=>{if(!open&&!c.busy)onClose();}}><DialogContent className="max-w-2xl max-h-[85vh] overflow-y-auto"><DialogHeader><DialogTitle>Create Card Batch</DialogTitle><DialogDescription>Select recorded payments for one processor. This is a manual group, not a supplied POS batch.</DialogDescription></DialogHeader>
 <label className="text-sm">Processor<select aria-label="Batch processor" className="block border rounded-md p-2 bg-background w-full" value={processor} onChange={e=>setProcessor(e.target.value)}><option value="">Choose processor</option>{data.processors.filter(p=>p.is_active).map(p=><option key={p.processor_id} value={p.processor_id}>{p.processor_name}</option>)}</select></label>
 <label className="text-sm">Business date<Input aria-label="Batch date" type="date" max={data.today} value={date} onChange={e=>{setDate(e.target.value);setSelected({});}}/></label>
 <label className="text-sm">Batch reference<Input aria-label="Batch reference" maxLength={100} value={reference} onChange={e=>setReference(e.target.value)}/></label>
 {q.isFetching&&<p>Loading available payments…</p>}{q.error&&<p role="alert">{q.error.message}</p>}
 <div className="border rounded-md max-h-56 overflow-y-auto">{q.data?.map(p=><label key={p.sale_payment_id} className="flex gap-3 items-center border-b p-2 text-sm"><input aria-label={`Select ${p.receipt_no} payment ${p.sale_payment_id}`} type="checkbox" checked={!!selected[p.sale_payment_id]} onChange={e=>setSelected(old=>{const next={...old};if(e.target.checked)next[p.sale_payment_id]=p.version;else delete next[p.sale_payment_id];return next;})}/><span>{p.receipt_no} · {p.tender_code}</span><span className="ml-auto">{fmt(p.amount)}</span></label>)}{q.data?.length===0&&<p className="p-3 text-sm">No unassigned card payments for this date.</p>}</div>
 <p className="text-sm">Selected: {Object.keys(selected).length} · {fmt(sum)}</p>{c.error&&<p role="alert" className="text-destructive">{c.error}</p>}
 <DialogFooter><Button variant="outline" disabled={c.busy} onClick={onClose}>Cancel</Button><Button disabled={c.busy||q.isFetching||!!q.error||!processor||!reference.trim()||!Object.keys(selected).length} onClick={()=>void c.mutate('/batches',{processorId:Number(processor),reference,date,requestKey:key,payments:selected}).then(onClose).catch(()=>{})}>Create Batch</Button></DialogFooter>
 </DialogContent></Dialog>;
}
export function BatchTransition({batch,action,onClose}:{batch:Batch;action:'SUBMIT'|'SETTLE'|'RECONCILE';onClose:()=>void}){
 const c=useCards();const [sales,setSales]=useState(''),[chargebacks,setChargebacks]=useState('0'),[reason,setReason]=useState(''),[received,setReceived]=useState(''),[date,setDate]=useState(c.q.data!.today),[reference,setReference]=useState(''),[note,setNote]=useState('');
 const title={SUBMIT:'Record Processor Statement',SETTLE:'Mark as Settled',RECONCILE:'Reconcile Batch'}[action];
 return <Dialog open onOpenChange={open=>{if(!open&&!c.busy)onClose();}}><DialogContent><DialogHeader><DialogTitle>{title} — {batch.batch_reference}</DialogTitle><DialogDescription>{action==='SUBMIT'?'Enter processor sales before the separately listed chargeback deduction.':`Destination: ${batch.settlement_destination} · ${batch.destination_label}. Expected net: ${fmt(net(batch))}. This records confirmation; it does not move funds.`}</DialogDescription></DialogHeader>
 {action==='SUBMIT'&&<><label>Processor sales<Input aria-label="Processor sales" value={sales} onChange={e=>setSales(e.target.value)}/></label><label>Chargebacks<Input aria-label="Chargebacks" value={chargebacks} onChange={e=>setChargebacks(e.target.value)}/></label><label>Chargeback reason<Input aria-label="Chargeback reason" value={reason} maxLength={1000} onChange={e=>setReason(e.target.value)}/></label></>}
 {action==='SETTLE'&&<><label>Amount received<Input aria-label="Amount received" value={received} onChange={e=>setReceived(e.target.value)}/></label><label>Settlement date<Input aria-label="Settlement date" type="date" min={batch.business_date} max={c.q.data!.today} value={date} onChange={e=>setDate(e.target.value)}/></label><label>Settlement reference<Input aria-label="Settlement reference" value={reference} maxLength={160} onChange={e=>setReference(e.target.value)}/></label></>}
 {action!=='SUBMIT'&&<label>Variance review note<Input aria-label="Variance review note" value={note} maxLength={1000} onChange={e=>setNote(e.target.value)}/><span className="text-xs text-muted-foreground">Required when a difference exceeds the configured tolerance.</span></label>}
 {c.error&&<p role="alert" className="text-destructive">{c.error}</p>}<DialogFooter><Button variant="outline" disabled={c.busy} onClick={onClose}>Cancel</Button><Button disabled={c.busy||action==='SUBMIT'&&(!sales.trim()||!chargebacks.trim()||!Number.isFinite(Number(sales))||!Number.isFinite(Number(chargebacks)))||action==='SETTLE'&&(!received.trim()||!Number.isFinite(Number(received))||!reference.trim()||!date)} onClick={()=>void c.mutate(`/batches/${batch.batch_id}/transition`,{version:batch.version,action,processorSales:action==='SUBMIT'?Number(sales):null,chargebacks:action==='SUBMIT'?Number(chargebacks):null,chargebackReason:reason,receivedAmount:action==='SETTLE'?Number(received):null,settlementDate:action==='SETTLE'?date:null,reference,reviewNote:note}).then(onClose).catch(()=>{})}>{title}</Button></DialogFooter>
 </DialogContent></Dialog>;
}
