package com.dgt.backend.pricebook;
import java.util.*;
import java.math.BigDecimal;
import java.time.LocalDate;
import com.dgt.backend.access.ScopedAccess;
import com.dgt.backend.common.entity.Rows;
import org.springframework.web.bind.annotation.*;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.boot.autoconfigure.condition.ConditionalOnProperty;
import org.springframework.http.HttpStatus;
import org.springframework.web.server.ResponseStatusException;
import tools.jackson.databind.ObjectMapper;
import lombok.extern.slf4j.Slf4j;
@Slf4j
@RestController
@ConditionalOnProperty(name="app.pricebook.enabled",havingValue="true")
@RequestMapping("/api/v1/access/stores/{store}/rebates")
public class StoreRebateController {
 private final ScopedAccess a;private final ObjectMapper json;
 public StoreRebateController(ScopedAccess a,ObjectMapper json){this.a=a;this.json=json;}
 private void access(String store){a.grant(a.user(),store,"PRICE_BOOK",true);}
 private void lock(String store){access(store);a.db.queryForList("SELECT dgt_id FROM stores WHERE dgt_id=? FOR UPDATE",store);}
 private ResponseStatusException bad(String s){return new ResponseStatusException(HttpStatus.BAD_REQUEST,s);}
 private ResponseStatusException conflict(){return new ResponseStatusException(HttpStatus.CONFLICT,"Record changed or is unavailable in this store; reload and retry");}
 private String text(Map<String,Object> m,String k,int max){String v=Objects.toString(m.get(k),"").trim();if(v.length()>max)throw bad(k+" is too long");return v;}
 private long number(Object x){try{return Long.parseLong(x.toString());}catch(Exception e){throw bad("Invalid record ID");}}
 private LocalDate date(Object x){try{return LocalDate.parse(x.toString());}catch(Exception e){throw bad("Choose valid dates");}}
 private Map<String,Object> one(String sql,Object... args){var r=a.db.queryForList(sql,args);if(r.size()!=1)throw bad("Record not found in this store");return r.getFirst();}
 @SuppressWarnings("unchecked") private Map<String,Object> settings(Object x){return json.readValue(x.toString(),Map.class);}
 private void choice(Map<String,Object> m,String key,String... values){if(!Set.of(values).contains(text(m,key,100)))throw bad("Choose a valid "+key);}
 private void decimal(Map<String,Object> m,String key,boolean required){String s=text(m,key,40);if(s.isEmpty()){if(required)throw bad("Enter "+key);return;}try{BigDecimal n=new BigDecimal(s);if(n.signum()<0||n.scale()>4||n.compareTo(new BigDecimal("9999999999"))>0)throw bad("Invalid "+key);}catch(NumberFormatException e){throw bad("Enter a numeric "+key);}}
 private Map<String,Object> program(String store,long id){return one("SELECT *,xmin::text AS version FROM rebate_programs WHERE program_id=? AND dgt_id=?",id,store);}
 private String status(Map<String,Object> p){String s=p.get("status").toString();if(!s.equals("Active"))return s;LocalDate now=a.db.queryForObject("SELECT (CURRENT_TIMESTAMP AT TIME ZONE timezone)::date FROM stores WHERE dgt_id=?",LocalDate.class,p.get("dgt_id"));return date(p.get("end_date")).isBefore(now)?"Expired":date(p.get("start_date")).isAfter(now)?"Upcoming":"Active";}
 private boolean eligible(String store,Map<String,Object> p,long product){var config=settings(p.get("settings"));String scope=Objects.toString(config.get("eligibilityScope"),"");
 var found=a.db.queryForList("SELECT * FROM products WHERE product_id=? AND dgt_id=? AND is_active",product,store);if(found.isEmpty())return false;var item=found.getFirst();
 return switch(scope){
 case "Specific Products" -> p.get("vendor_id")==null || !a.db.queryForList("SELECT product_vendor_id FROM product_vendors WHERE product_vendors.archived_at IS NULL AND product_id=? AND vendor_id=? AND dgt_id=?",product,p.get("vendor_id"),store).isEmpty();
 case "All Products from Provider" -> !a.db.queryForList("SELECT product_vendor_id FROM product_vendors WHERE product_vendors.archived_at IS NULL AND product_id=? AND vendor_id=? AND dgt_id=?",product,p.get("vendor_id"),store).isEmpty();
 case "Department" -> !a.db.queryForList("SELECT store_sub_department_id FROM store_sub_departments WHERE store_sub_department_id=? AND store_department_id=? AND dgt_id=?",item.get("store_sub_department_id"),number(config.get("scopeValue")),store).isEmpty();
 case "Subdepartment" -> Objects.equals(item.get("store_sub_department_id"),number(config.get("scopeValue")));
 case "Brand" -> Objects.equals(item.get("brand_id"),number(config.get("scopeValue")));
 default -> false;};
 }
 private Map<String,Object> view(Map<String,Object> row){var p=new LinkedHashMap<>(settings(row.get("settings")));String store=row.get("dgt_id").toString();long id=number(row.get("program_id"));
 p.put("id",Long.toString(id));p.put("version",row.get("version"));p.put("name",row.get("name"));p.put("vendorId",row.get("vendor_id")==null?"":row.get("vendor_id").toString());p.put("vendor",row.get("provider_name"));p.put("startDate",row.get("start_date").toString());p.put("endDate",row.get("end_date").toString());p.put("status",status(row));
 var ids=a.db.queryForList("SELECT product_id FROM rebate_program_items WHERE program_id=? AND dgt_id=? AND active ORDER BY product_id",Long.class,id,store);p.put("selectedProductIds",ids.stream().map(Object::toString).toList());p.put("selectedProductCount",ids.size());p.put("eligibleItems",p.get("eligibilityScope")+ ("Specific Products".equals(p.get("eligibilityScope"))?" ("+ids.size()+")":""));return p;}
 @GetMapping public Object list(@PathVariable String store){access(store);
 var programs=a.db.queryForList("SELECT *,xmin::text AS version FROM rebate_programs WHERE dgt_id=? ORDER BY program_id DESC",store).stream().map(this::view).toList();
 var items=a.db.queryForList("SELECT l.link_id::text AS id,l.xmin::text AS version,l.product_id::text AS \"productId\",l.program_id::text AS \"programId\",p.product_name AS \"itemName\",coalesce((SELECT min(b.product_barcode_value) FROM product_barcodes b WHERE b.archived_at IS NULL AND b.product_id=p.product_id),'') AS upc,r.name AS \"programName\",r.provider_name AS \"rebateProvider\",r.settings->>'rebateType' AS \"rebateType\",coalesce(l.start_date,r.start_date)::text AS \"startDate\",coalesce(l.end_date,r.end_date)::text AS \"endDate\",l.rebate_terms AS \"rebateAmount\",CASE WHEN NOT l.active OR r.status='Inactive' THEN 'Inactive' WHEN r.status='Draft' THEN 'Draft' WHEN coalesce(l.end_date,r.end_date)<(CURRENT_TIMESTAMP AT TIME ZONE s.timezone)::date THEN 'Expired' WHEN coalesce(l.start_date,r.start_date)>(CURRENT_TIMESTAMP AT TIME ZONE s.timezone)::date THEN 'Upcoming' ELSE 'Active' END AS status FROM rebate_program_items l JOIN rebate_programs r ON r.program_id=l.program_id AND r.dgt_id=l.dgt_id JOIN products p ON p.product_id=l.product_id AND p.dgt_id=l.dgt_id JOIN stores s ON s.dgt_id=l.dgt_id WHERE l.dgt_id=? ORDER BY l.link_id DESC",store);
 var products=a.db.queryForList("SELECT p.product_id::text AS id,p.product_name AS name,p.product_sku AS sku,coalesce((SELECT min(b.product_barcode_value) FROM product_barcodes b WHERE b.archived_at IS NULL AND b.product_id=p.product_id),'') AS barcode FROM products p WHERE p.dgt_id=? AND p.is_active ORDER BY p.product_name",store);
 return Map.of("productVendorLinks",a.db.queryForList("SELECT product_id::text AS \"productId\",vendor_id::text AS \"vendorId\" FROM product_vendors WHERE product_vendors.archived_at IS NULL AND dgt_id=?",store),"programs",programs,"items",items.stream().map(Rows::normalize).toList(),"products",products,"vendors",a.db.queryForList("SELECT vendor_id::text AS id,vendor_name AS name FROM vendors WHERE dgt_id=? AND is_active ORDER BY vendor_name",store),"departments",a.db.queryForList("SELECT store_department_id::text AS id,store_department_name AS name FROM store_departments WHERE dgt_id=?",store),"subdepartments",a.db.queryForList("SELECT store_sub_department_id::text AS id,store_sub_department_name AS name FROM store_sub_departments WHERE dgt_id=?",store),"brands",a.db.queryForList("SELECT DISTINCT b.brand_id::text AS id,b.brand_name AS name FROM brands b JOIN products p ON p.brand_id=b.brand_id WHERE p.dgt_id=?",store));
 }
 @PostMapping("/programs") @Transactional public Object create(@PathVariable String store,@RequestBody Map<String,Object> in){return save(store,null,null,in);}
 @PutMapping("/programs/{id}") @Transactional public Object update(@PathVariable String store,@PathVariable long id,@RequestHeader("If-Match") String version,@RequestBody Map<String,Object> in){return save(store,id,version,in);}
 private Object save(String store,Long id,String version,Map<String,Object> in){lock(store);if(id!=null&&!Objects.equals(program(store,id).get("version"),version))throw conflict();
 if(id!=null&&"Inactive".equals(in.get("status"))){a.db.update("UPDATE rebate_programs SET status='Inactive',updated_at=now() WHERE program_id=?",id);a.audit(store,"REBATE_PROGRAM_DEACTIVATED",id.toString(),"{}");return Map.of("id",id,"saved",true);}
 String name=text(in,"name",150);if(name.isEmpty())throw bad("Enter a program name");String provider=text(in,"vendor",200);Long vendor=null;
 choice(in,"offeredByType","Vendor / Distributor","Manufacturer","Other");
 if("Vendor / Distributor".equals(in.get("offeredByType"))){vendor=number(in.get("vendorId"));provider=one("SELECT vendor_name FROM vendors WHERE vendor_id=? AND dgt_id=? AND is_active",vendor,store).get("vendor_name").toString();}if(provider.isBlank())throw bad("Enter a provider");
 choice(in,"rebateType","Volume / Purchase","Tiered","Percentage","Per unit","Compliance","Display","Promotional","Growth");choice(in,"eligibilityScope","All Products from Provider","Department","Subdepartment","Brand","Specific Products");choice(in,"status","Draft","Active","Inactive");choice(in,"qualificationType","Purchase Amount","Quantity","Cases","Sales Amount","Growth %","Display Requirement","Promotion Participation","Compliance","No Minimum Requirement");choice(in,"measurementBasis","Purchases","Sales","Units Received","Cases Received");choice(in,"rewardType","Percentage","Fixed Amount","Per Unit","Per Case","Account Credit","Free Goods","Other");choice(in,"calculation","On qualifying purchases","On total purchases","On qualifying units","Flat on qualification");choice(in,"claimFrequency","Monthly","Quarterly","Semi-Annual","Annual");choice(in,"paymentMethod","Vendor Credit","Check","ACH Transfer","Wire Transfer","Free Goods");
 LocalDate start=date(in.get("startDate")),end=date(in.get("endDate"));if(end.isBefore(start))throw bad("End date must not precede start date");
 String scope=text(in,"eligibilityScope",100);String scopeValue=text(in,"scopeValue",50);
 if(scope.equals("All Products from Provider")&&vendor==null)throw bad("Choose specific products or a classification for non-vendor providers");
 if(scope.equals("Department"))one("SELECT store_department_id FROM store_departments WHERE store_department_id=? AND dgt_id=?",number(scopeValue),store);
 if(scope.equals("Subdepartment"))one("SELECT store_sub_department_id FROM store_sub_departments WHERE store_sub_department_id=? AND dgt_id=?",number(scopeValue),store);
 if(scope.equals("Brand"))one("SELECT DISTINCT brand_id FROM products WHERE brand_id=? AND dgt_id=?",number(scopeValue),store);
 boolean activating="Active".equals(in.get("status"));
 decimal(in,"target",activating&&Set.of("Purchase Amount","Quantity","Cases","Sales Amount","Growth %").contains(in.get("qualificationType")));
 decimal(in,"rewardValue",activating&&!"Tiered".equals(in.get("rebateType"))&&Set.of("Percentage","Fixed Amount","Per Unit","Per Case","Account Credit").contains(in.get("rewardType")));
 decimal(in,"submissionDeadlineDays",Boolean.TRUE.equals(in.get("claimRequired")));
 if(!text(in,"submissionDeadlineDays",40).isEmpty()&&new BigDecimal(text(in,"submissionDeadlineDays",40)).stripTrailingZeros().scale()>0)throw bad("Submission deadline must be whole days");
 if("Percentage".equals(in.get("rewardType"))&&!text(in,"rewardValue",40).isEmpty()&&new BigDecimal(text(in,"rewardValue",40)).compareTo(new BigDecimal("100"))>0)throw bad("Percentage cannot exceed 100");
 if(!(in.get("claimRequired") instanceof Boolean))throw bad("Choose whether a claim is required");
 var config=new LinkedHashMap<String,Object>();for(String key:List.of("offeredByType","description","rebateType","eligibilityScope","scopeValue","qualificationType","target","measurementBasis","rewardType","rewardValue","calculation","claimFrequency","claimRequired","submissionDeadlineDays","paymentMethod")){Object value=in.get(key);if(value instanceof String s&&s.length()>2000)throw bad(key+" is too long");if(!key.equals("claimRequired")&&value!=null&&!(value instanceof String))throw bad("Invalid "+key);config.put(key,key.equals("claimRequired")?value:Objects.toString(value,""));}
 Object raw=in.get("tiers");if(!(raw instanceof List<?> tiers)||tiers.size()>100)throw bad("Invalid tiers");
 if("Tiered".equals(in.get("rebateType"))){if(tiers.isEmpty())throw bad("Add at least one tier");BigDecimal previous=null;for(Object t:tiers){if(!(t instanceof Map<?,?>))throw bad("Invalid tier");@SuppressWarnings("unchecked") var tier=(Map<String,Object>)t;decimal(tier,"from",true);decimal(tier,"to",false);String reward=text(tier,"reward",200);if(reward.isBlank())throw bad("Enter a tier reward");BigDecimal from=new BigDecimal(text(tier,"from",40));if(previous!=null&&from.compareTo(previous)<=0)throw bad("Tier ranges must not overlap");if(text(tier,"to",40).isBlank()){if(t!=tiers.getLast())throw bad("Only the last tier may have no upper limit");}else{previous=new BigDecimal(text(tier,"to",40));if(previous.compareTo(from)<0)throw bad("Invalid tier range");}}config.put("tiers",tiers);}else config.put("tiers",List.of());
 List<Long> selected=new ArrayList<>();if(scope.equals("Specific Products")){if(!(in.get("selectedProductIds") instanceof List<?> ids)||ids.size()>1000)throw bad("Choose specific products");for(Object product:ids){long pid=number(product);one("SELECT product_id FROM products WHERE product_id=? AND dgt_id=? AND is_active",pid,store);if(vendor!=null && a.db.queryForList("SELECT product_vendor_id FROM product_vendors WHERE product_vendors.archived_at IS NULL AND product_id=? AND vendor_id=? AND dgt_id=?",pid,vendor,store).isEmpty())throw bad("Select products linked to the selected vendor");if(selected.contains(pid))throw bad("Select each product once");selected.add(pid);}}
 if(id==null)id=a.db.queryForObject("INSERT INTO rebate_programs(dgt_id,vendor_id,name,provider_name,start_date,end_date,status,settings) VALUES (?,?,?,?,?,?,?,CAST(? AS jsonb)) RETURNING program_id",Long.class,store,vendor,name,provider,start,end,in.get("status"),json.writeValueAsString(config));
 else{for(var link:a.db.queryForList("SELECT start_date,end_date FROM rebate_program_items WHERE program_id=? AND active",id)){if(link.get("start_date")!=null&&date(link.get("start_date")).isBefore(start)||link.get("end_date")!=null&&date(link.get("end_date")).isAfter(end))throw bad("Update linked item dates before narrowing program dates");}a.db.update("UPDATE rebate_programs SET vendor_id=?,name=?,provider_name=?,start_date=?,end_date=?,status=?,settings=CAST(? AS jsonb),updated_at=now() WHERE program_id=?",vendor,name,provider,start,end,in.get("status"),json.writeValueAsString(config),id);}
 if(scope.equals("Specific Products")){a.db.update("UPDATE rebate_program_items SET active=false,updated_at=now() WHERE program_id=?",id);for(long pid:selected)a.db.update("INSERT INTO rebate_program_items(dgt_id,program_id,product_id) VALUES (?,?,?) ON CONFLICT(program_id,product_id) DO UPDATE SET active=true,updated_at=now()",store,id,pid);}
 else {var p=program(store,id);for(var link:a.db.queryForList("SELECT link_id,product_id FROM rebate_program_items WHERE program_id=? AND active",id))if(!eligible(store,p,number(link.get("product_id"))))a.db.update("UPDATE rebate_program_items SET active=false,updated_at=now() WHERE link_id=?",link.get("link_id"));}
 a.audit(store,"REBATE_PROGRAM_SAVED",id.toString(),json.writeValueAsString(config));return Map.of("id",id,"saved",true);
 }
 public record Link(long productId,long programId,String startDate,String endDate,String rebateAmount,boolean active){}
 @PostMapping("/items") @Transactional public Object add(@PathVariable String store,@RequestBody Link in){return link(store,null,null,in);}
 @PutMapping("/items/{id}") @Transactional public Object edit(@PathVariable String store,@PathVariable long id,@RequestHeader("If-Match") String version,@RequestBody Link in){return link(store,id,version,in);}
 private Object link(String store,Long id,String version,Link in){lock(store);
 if(id!=null&&!in.active()){var old=one("SELECT *,xmin::text AS version FROM rebate_program_items WHERE link_id=? AND dgt_id=?",id,store);if(!Objects.equals(old.get("version"),version))throw conflict();a.db.update("UPDATE rebate_program_items SET active=false,updated_at=now() WHERE link_id=?",id);a.db.update("UPDATE rebate_programs SET updated_at=now() WHERE program_id=?",old.get("program_id"));a.audit(store,"REBATE_ITEM_DEACTIVATED",id.toString(),"{}");return Map.of("id",id,"saved",true);}
 var p=program(store,in.programId());if("Inactive".equals(p.get("status"))&&in.active())throw bad("Program is inactive");if(in.active()&&!eligible(store,p,in.productId()))throw bad("Item does not match the program eligibility scope");
 LocalDate start=in.startDate()==null||in.startDate().isBlank()?null:date(in.startDate()),end=in.endDate()==null||in.endDate().isBlank()?null:date(in.endDate());LocalDate effectiveStart=start==null?date(p.get("start_date")):start,effectiveEnd=end==null?date(p.get("end_date")):end;if(effectiveEnd.isBefore(effectiveStart)||effectiveStart.isBefore(date(p.get("start_date")))||effectiveEnd.isAfter(date(p.get("end_date"))))throw bad("Item dates must be inside the program dates");if(in.rebateAmount()!=null&&in.rebateAmount().length()>1000)throw bad("Rebate terms are too long");
 if(id==null){if(!a.db.queryForList("SELECT link_id FROM rebate_program_items WHERE program_id=? AND product_id=?",in.programId(),in.productId()).isEmpty())throw conflict();id=a.db.queryForObject("INSERT INTO rebate_program_items(dgt_id,program_id,product_id,start_date,end_date,rebate_terms,active) VALUES (?,?,?,?,?,?,?) RETURNING link_id",Long.class,store,in.programId(),in.productId(),start,end,Objects.toString(in.rebateAmount(),""),in.active());}
 else{var old=one("SELECT *,xmin::text AS version FROM rebate_program_items WHERE link_id=? AND dgt_id=?",id,store);if(!Objects.equals(old.get("version"),version))throw conflict();if(number(old.get("program_id"))!=in.programId()||number(old.get("product_id"))!=in.productId())throw bad("Deactivate this link and add the item to the other program");a.db.update("UPDATE rebate_program_items SET start_date=?,end_date=?,rebate_terms=?,active=?,updated_at=now() WHERE link_id=?",start,end,Objects.toString(in.rebateAmount(),""),in.active(),id);}
 a.db.update("UPDATE rebate_programs SET updated_at=now() WHERE program_id=?",in.programId());a.audit(store,"REBATE_ITEM_SAVED",id.toString(),"{}");return Map.of("id",id,"saved",true);
 }
 @GetMapping("/programs/{id}/eligible") public Object eligibleProducts(@PathVariable String store,@PathVariable long id){access(store);var p=program(store,id);boolean specific="Specific Products".equals(settings(p.get("settings")).get("eligibilityScope"));var excluded=a.db.queryForList("SELECT product_id FROM rebate_program_items WHERE program_id=? AND NOT active",Long.class,id);var linked=a.db.queryForList("SELECT product_id FROM rebate_program_items WHERE program_id=? AND active",Long.class,id);return a.db.queryForList("SELECT p.product_id::text AS id,p.product_name AS name,coalesce((SELECT min(product_barcode_value) FROM product_barcodes WHERE product_barcodes.archived_at IS NULL AND product_id=p.product_id),'') AS upc FROM products p WHERE dgt_id=? AND is_active ORDER BY product_name",store).stream().filter(i->specific?linked.contains(number(i.get("id")))&&eligible(store,p,number(i.get("id"))):!excluded.contains(number(i.get("id")))&&eligible(store,p,number(i.get("id")))).toList();}
}
