import {useState} from 'react';
import {useQuery} from '@tanstack/react-query';
import {format,parseISO,subDays,startOfWeek,startOfMonth} from 'date-fns';
import {Activity,Printer,Download,DollarSign,Receipt,CreditCard,Banknote,TrendingUp,AlertTriangle,ShoppingCart,Filter,ChevronDown,RefreshCw,CalendarCheck,WifiOff,Fuel,BarChart3} from 'lucide-react';
import {Card,CardContent,CardHeader,CardTitle} from '@/components/ui/card';
import {Badge} from '@/components/ui/badge';
import {Button} from '@/components/ui/button';
import {Switch} from '@/components/ui/switch';
import {Input} from '@/components/ui/input';
import {Table,TableBody,TableCell,TableHead,TableHeader,TableRow} from '@/components/ui/table';
import {request} from '@/lib/backend';
import {type ActivityData,type Transaction,money,when,downloadTransactions} from './liveActivityData';
import {LiveTransactionDetail} from './LiveTransactionDrawer';
export const LiveCounterPage=({storeId,onOpenDailyClosing}:{storeId:string;onOpenDailyClosing:()=>void})=>{
 const path=`/access/stores/${encodeURIComponent(storeId)}/live-activity`;
 const [auto,setAuto]=useState(true),[expanded,setExpanded]=useState<string|null>(null),[terminal,setTerminal]=useState('all'),[type,setType]=useState('ALL'),[preset,setPreset]=useState('latest'),[start,setStart]=useState(''),[end,setEnd]=useState(''),[page,setPage]=useState(1),[exporting,setExporting]=useState(false),[exportError,setExportError]=useState('');
 const meta=useQuery({queryKey:['activity-meta',storeId],queryFn:()=>request<ActivityData>(path+'?size=1'),refetchInterval:auto?15000:false,refetchOnWindowFocus:true});
 const info=meta.data;let from='',to='';if(info){const today=parseISO(info.today);from=info.today;to=info.today;if(preset==='latest')from=to=info.range.last??info.today;if(preset==='all'){from=info.range.first??info.today;to=info.range.last??info.today;}if(preset==='yesterday')from=to=format(subDays(today,1),'yyyy-MM-dd');if(preset==='week')from=format(startOfWeek(today,{weekStartsOn:1}),'yyyy-MM-dd');if(preset==='month')from=format(startOfMonth(today),'yyyy-MM-dd');if(preset==='custom'){from=start;to=end||start;}}
 const valid=!!from&&!!to&&from<=to;const params=new URLSearchParams({start:from,end:to,type,page:String(page),size:'8'});if(terminal!=='all')params.set('terminal',terminal);
 const q=useQuery({queryKey:['live-activity',storeId,from,to,terminal,type,page],queryFn:()=>request<ActivityData>(path+'?'+params),enabled:!!info&&valid,refetchInterval:auto?5000:false,refetchOnWindowFocus:true});
 const data=q.data;
 const filter=(f:()=>void)=>{f();setPage(1);setExpanded(null);};
 const exportAll=async()=>{if(!data)return;setExporting(true);setExportError('');try{const all:Transaction[]=[];const p=new URLSearchParams(params);p.set('size','100');for(let n=1;n<=Math.ceil(data.stats.transactions/100);n++){p.set('page',String(n));const result=await request<ActivityData>(path+'?'+p);all.push(...result.transactions);}downloadTransactions(all,data.timezone);}catch(e){setExportError((e as Error).message);}finally{setExporting(false);}};
 if(meta.isPending)return <p>Loading sales activity…</p>;
 if(meta.error)return <p role="alert">{meta.error.message}<Button onClick={()=>meta.refetch()}>Retry</Button></p>;
 const tender=(codes:string[])=>data?.tenders.filter(t=>codes.includes(t.code)).reduce((s,t)=>s+Number(t.amount),0)??0;
 const kpis=data?[{label:preset==='today'?'Sales Today':'Sales',value:money(data.stats.netSales),icon:DollarSign},{label:'Transactions',value:String(data.stats.transactions),icon:Receipt},{label:'Avg Ticket',value:money(data.stats.averageTicket),icon:TrendingUp},{label:preset==='today'?'Cash Today':'Cash',value:money(tender(['CASH'])),icon:Banknote},{label:preset==='today'?'Card Today':'Card / Mobile',value:money(tender(['CREDIT_CARD','DEBIT_CARD','MOBILE_PAY'])),icon:CreditCard}]:[];
 const paid=data?.tenders.reduce((s,t)=>s+Number(t.amount),0)??0;
 return <div className="space-y-7"><div className="flex flex-wrap items-center justify-between gap-4"><div className="flex items-center gap-2"><Activity className="w-6 h-6 text-emerald-500"/><h1 className="text-2xl font-bold tracking-tight">Live Counter</h1></div><div className="flex flex-wrap items-center gap-3 print:hidden"><Badge variant="outline" className="gap-1.5 rounded-full text-muted-foreground"><WifiOff className="h-3.5 w-3.5"/>POS not connected</Badge><span className="text-xs text-muted-foreground" title={data?when(data.asOf,data.timezone):undefined}>Last sync: {data?new Intl.DateTimeFormat('en-US',{timeZone:data.timezone,timeStyle:'short'}).format(new Date(data.asOf)):'—'}</span><label className="flex gap-2 items-center text-sm text-muted-foreground">Auto refresh<Switch aria-label="Auto refresh" checked={auto} onCheckedChange={setAuto}/></label><Button variant="outline" size="sm" onClick={()=>{void meta.refetch();void q.refetch();}} aria-label="Refresh" title="Refresh" disabled={q.isFetching}><RefreshCw className="w-4 h-4"/><span className="sr-only">Refresh</span></Button><Button variant="outline" size="sm" onClick={()=>window.print()}><Printer className="w-3.5 h-3.5 mr-1"/>Print</Button><Button variant="outline" size="sm" disabled={!data||!data.stats.transactions||exporting} onClick={exportAll}><Download className="w-3.5 h-3.5 mr-1"/>{exporting?'Exporting…':'Export'}</Button><Button variant="secondary" size="sm" onClick={onOpenDailyClosing}><CalendarCheck className="w-4 h-4 mr-2"/>Open Daily Closing</Button></div></div>
 <div className="flex flex-wrap items-center gap-3 print:hidden"><Filter className="w-4 h-4 text-muted-foreground"/><select aria-label="Date filter" className="border rounded-xl h-10 px-3 text-sm bg-background min-w-[180px]" value={preset} onChange={e=>filter(()=>setPreset(e.target.value))}>{[['latest','Latest sales date'],['today','Today'],['yesterday','Yesterday'],['week','This Week'],['month','This Month'],['all','All available dates'],['custom','Custom dates']].map(([v,label])=><option key={v} value={v}>{label}</option>)}</select>
 {preset==='custom'&&<><Input className="w-40 h-8" aria-label="Start date" type="date" value={start} onChange={e=>filter(()=>setStart(e.target.value))}/><Input className="w-40 h-8" aria-label="End date" type="date" value={end} onChange={e=>filter(()=>setEnd(e.target.value))}/></>}
 <select aria-label="Terminal filter" className="border rounded-xl h-10 px-3 text-sm bg-background min-w-[180px]" value={terminal} onChange={e=>filter(()=>setTerminal(e.target.value))}><option value="all">All POS</option>{info?.terminals.map(t=><option key={t.id} value={t.id}>{t.code}</option>)}</select>
 <select aria-label="Transaction filter" className="border rounded-xl h-10 px-3 text-sm bg-background min-w-[180px]" value={type} onChange={e=>filter(()=>setType(e.target.value))}>{[['ALL','All Transactions'],['SALE','Sale'],['RETURN','Return'],['REFUND','Refund'],['VOID','Void']].map(([v,label])=><option key={v} value={v}>{label}</option>)}</select></div>
 {!valid&&<p role="alert">Choose a valid start and end date.</p>}{q.isPending&&valid&&<p>Loading transactions…</p>}{q.error&&<p role="alert" className="text-destructive">{q.error.message}<Button onClick={()=>q.refetch()}>Retry</Button></p>}{exportError&&<p role="alert">{exportError}</p>}
 {data&&<><p className="text-xs text-muted-foreground">{data.start} – {data.end} · {data.timezone}{data.importedWorkbook?' · Original sale dates':''}</p>
 <div className="grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-5 gap-4">{kpis.map(k=><Card key={k.label} className="border-border/60"><CardContent className="p-5 min-h-[120px] flex flex-col gap-2"><div className="flex items-center gap-1.5 text-muted-foreground"><k.icon className="w-3.5 h-3.5"/><span className="text-sm font-medium">{k.label}</span></div><span className="text-2xl font-bold">{k.value}</span></CardContent></Card>)}</div>
 <div className="grid grid-cols-1 lg:grid-cols-5 gap-7"><div className="lg:col-span-3 space-y-3"><h2 className="text-base font-semibold flex items-center gap-2"><Receipt className="w-4 h-4 text-primary"/>Recent Transactions<span className={`ml-1 h-2 w-2 rounded-full ${auto?'bg-emerald-500':'bg-muted-foreground'}`} title={auto?'Auto refresh enabled':'Auto refresh paused'}/></h2>
 {!data.transactions.length&&<Card><CardContent className="p-5 text-sm">No transactions for these filters.{info?.range.last&&preset==='today'&&<Button variant="link" onClick={()=>filter(()=>setPreset('latest'))}>View latest sales date ({info.range.last})</Button>}</CardContent></Card>}
 <div className="border-l-2 border-muted pl-3 space-y-2.5">{data.transactions.map(tx=><Card key={tx.id} className="border-border/50 rounded-2xl shadow-sm"><CardContent className="p-0"><button className="w-full text-left flex items-center justify-between gap-3 px-4 py-4 min-h-[58px]" aria-label={`Receipt ${tx.receipt}, ${tx.status}`} aria-expanded={expanded===tx.id} onClick={()=>setExpanded(expanded===tx.id?null:tx.id)}><div className="flex flex-wrap gap-x-3 gap-y-2 items-center text-sm text-muted-foreground"><span>{when(tx.time,data.timezone)}</span><Badge variant="outline" className="rounded-full px-2 py-0 text-[10px] text-foreground">{tx.terminal}</Badge><span className="font-mono">{tx.receipt}</span><span className="flex items-center gap-1.5">{tx.payments.some(p=>p.code==='CASH')?<Banknote className="h-4 w-4 text-emerald-500"/>:<CreditCard className="h-4 w-4 text-blue-500"/>}{tx.payments.map(p=>p.name).join(' / ')||'No payment'}</span>{tx.discount>0&&<Badge className="rounded-full bg-blue-100 text-blue-600 border-blue-200 px-2 py-0 hover:bg-blue-100">Discount</Badge>}{(tx.type!=='SALE'||tx.status!=='COMPLETED')&&<Badge className="rounded-full bg-red-100 text-red-600 px-2 py-0 hover:bg-red-100">{tx.type==='SALE'?tx.status:tx.type}</Badge>}</div><div className="flex items-center gap-3 shrink-0"><span className="text-base font-bold">{money(tx.total)}</span><ChevronDown className={`w-4 h-4 text-muted-foreground ${expanded===tx.id?'rotate-180':''}`}/></div></button>{expanded===tx.id&&<div className="px-5 pb-5"><p className="text-xs text-muted-foreground mb-3">Cashier: {tx.cashier} · {tx.status}</p><LiveTransactionDetail transaction={tx} path={path}/></div>}</CardContent></Card>)}</div>
 <div className="flex justify-end items-center gap-3 text-xs print:hidden"><Button variant="outline" size="sm" disabled={page<=1} onClick={()=>{setPage(page-1);setExpanded(null);}}>Previous</Button><span>{page} / {Math.max(1,Math.ceil(data.stats.transactions/8))}</span><Button variant="outline" size="sm" disabled={page*8>=data.stats.transactions} onClick={()=>{setPage(page+1);setExpanded(null);}}>Next</Button></div></div>
 <div className="lg:col-span-2 space-y-6"><Card><CardHeader className="pb-3 pt-5 px-5"><CardTitle className="text-sm tracking-wide uppercase text-muted-foreground">Tender Running Totals</CardTitle></CardHeader><CardContent className="px-5 pb-5"><Table className="[&_td]:py-2 [&_th]:h-9"><TableHeader><TableRow><TableHead>Type</TableHead><TableHead className="text-right">Amount</TableHead></TableRow></TableHeader><TableBody>{data.tenders.map(t=><TableRow key={t.code}><TableCell className="text-sm">{t.name}</TableCell><TableCell className="text-sm text-right">{money(t.amount)}</TableCell></TableRow>)}<TableRow><TableCell className="font-bold">Total</TableCell><TableCell className="text-right font-bold">{money(paid)}</TableCell></TableRow></TableBody></Table></CardContent></Card>
 <Card><CardHeader className="pb-3 pt-5 px-5"><CardTitle className="text-sm tracking-wide uppercase flex gap-1 text-muted-foreground"><AlertTriangle className="w-3.5 h-3.5 text-amber-500"/>Alerts</CardTitle></CardHeader><CardContent className="px-5 pb-5 text-xs space-y-2">{Math.abs(paid-data.stats.netSales)>.01?<p className="rounded-xl bg-orange-50 p-3 text-orange-700">Net sales and recorded payments differ by {money(data.stats.netSales-paid)}. Review payment statuses.</p>:<p className="rounded-xl bg-emerald-50 p-3 text-emerald-700">Recorded payments match net sales for these filters.</p>}<p className="rounded-xl bg-amber-50 p-3 text-amber-700">POS connectivity, no-sale events, suspended transactions and line void events are not supplied by this workbook.</p></CardContent></Card>
 <Card><CardHeader className="pb-3 pt-5 px-5"><CardTitle className="text-sm tracking-wide uppercase flex gap-1 text-muted-foreground"><ShoppingCart className="w-3.5 h-3.5"/>Top Selling Items</CardTitle></CardHeader><CardContent className="px-5 pb-5"><Table className="[&_td]:py-2 [&_th]:h-9"><TableHeader><TableRow><TableHead>Item</TableHead><TableHead className="text-right">Quantity</TableHead><TableHead className="text-right">Sales</TableHead></TableRow></TableHeader><TableBody>{data.topItems.slice(0,5).map(i=><TableRow key={i.id}><TableCell className="text-sm">{i.name}</TableCell><TableCell className="text-sm text-right">{Number(i.quantity).toLocaleString()} {i.unit}</TableCell><TableCell className="text-sm text-right">{money(i.amount)}</TableCell></TableRow>)}</TableBody></Table></CardContent></Card></div></div>
 <div className="grid grid-cols-2 sm:grid-cols-4 lg:grid-cols-7 gap-4">{[
 {label:'Grocery Sales',value:money(data.departments.filter(d=>['grocery','dairy & groceries'].includes(d.name.toLowerCase())).reduce((sum,d)=>sum+Number(d.amount),0)),icon:ShoppingCart,color:''},
 {label:'Gas Volume',value:`${Number(data.stats.gasVolume??0).toLocaleString('en-US',{maximumFractionDigits:3})} gal`,icon:Fuel,color:'',hint:'Completed Fuel/Gas sales in gallons, less completed fuel returns/refunds, for the selected filters.'},
 {label:'Gas Grades',value:'—',icon:BarChart3,color:'',hint:'Active fuel grade counts are not connected to this view yet.'},
 {label:'No. of Sales',value:String(data.stats.saleCount),icon:Receipt,color:'text-blue-600'},
 {label:'No. of No Sale',value:'—',icon:Activity,color:'text-red-500'},
 {label:'No. of Void Line',value:'—',icon:AlertTriangle,color:'text-amber-500'},
 {label:'No. of Suspend Txns',value:'—',icon:AlertTriangle,color:'text-red-500'}
 ].map(s=><Card key={s.label}><CardContent className="p-5" title={s.hint??(s.value==='—'?'Not supplied by the sales source':undefined)}><p className="text-xs font-medium text-muted-foreground flex items-center gap-2"><s.icon className={`h-4 w-4 shrink-0 ${s.color}`}/>{s.label}</p><p className={`text-xl font-bold mt-2 ${s.color}`}>{s.value}</p></CardContent></Card>)}</div>
 <details className="text-sm"><summary className="cursor-pointer text-muted-foreground">Sales by Department</summary><div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-4 p-4">{data.departments.map((d,i)=><div key={i}><p className="text-muted-foreground">{d.name}</p><p className="font-semibold">{money(d.amount)}</p></div>)}</div></details>
 </>}
 </div>;
};
